### ISSUE TITLE
Can't get sub-items working correctly

### ISSUE THREAD

**Issue by adammpkins** [lavary/laravel-menu#103]
I am using [Lavary's laravel-menu package][1], and I am trying to build a simple 2 level menu system based on the contents of a db table. I have the middleware created to create the menu on each request:

    public function handle($request, Closure $next)
    {
        Menu::make('NavBar', function($menu){
            $menuitems = MenuItem::all();
            foreach($menuitems as $menuitem)
            {
                if(!is_null($menuitem->parent)){
                   // For example, 'Conferences', a top level menu item with a null parent field
                   $menu->add($menuitem->title, url($menuitem->url));
                }
                else{
                    // Parent is a field in database, for example 'Traverse City 2015' would have the parent 'conferences'
                    $parent = $menuitem->parent;
                    $menu->item($parent)->add($menuitem->title, url($menuitem->url));

                }
            }
        });
        return $next($request);
    }
    

In my view, I call:

    {!! $NavBar->asUl() !!}

I would expect this to render as such:

    <ul>
      <li><a href="/conferences">Conferences</a></li>
      <ul>
        <li><a href="/conferences/traverse-city-2015">Traverse City 2015</li>
      </ul>
    </ul>

Instead, it is rendering:

    <ul>
      <li><a href="/conferences/">Conferences</a></li>
      <li><a href="/conferences/traverse-city-2015">Traverse City 2015</a></li>
    </ul>

Any ideas why the sub-items aren't showing up correctly?

  [1]: https://github.com/lavary/laravel-menu#sub-items

**Comment by EuropeanRespiratorySociety** [comment]
I think there is something wrong with
    $menu->item($parent)->add($menuitem->title, url($menuitem->url));

To find the instance of the parent maybe try:
     $parent = menu->find($menuitem->parent);    

Then something like
    $menu->$parent['nickname']->add($menuitem->title, url($menuitem->url));

**Comment by adammpkins** [comment]
I'm fairly sure that children are simply broken in this package. None of the readme's examples for sub-items or groups work either. 

This code produces the same issue. 

```
    <?php
Menu::make('MyNavBar', function($menu){

  $menu->add('Home',     array('route'  => 'home.page', 'class' => 'navbar navbar-home', 'id' => 'home'));

  $menu->group(array('style' => 'padding: 0', 'data-role' => 'navigation') function($m){

        $m->add('About',    array('route'  => 'page.about', 'class' => 'navbar navbar-about dropdown'));
        $m->add('services', array('action' => 'ServicesController@index'));
  }

  $menu->add('Contact',  'contact');

});
?>
```

**Comment by lavary** [comment]
@adammpkins Sorry for the delayed reply.

shouldn't `if(!is_null($menuitem->parent)){`  be `if(is_null($menuitem->parent)){`   ?

You're checking if `parent` is **not** `null`, and if it's true, you add the item to the root level.

Just note that `item()` method accepts nicknames, if you're storing the an ID number in the `parent` property, then you should use `find()` method instead.

**Comment by adammpkins** [comment]
It was my own oversight. The field was empty, but not truly null. Also, you were right. I did have the logic reversed. Thanks for your time!

**Comment by Landish** [comment]
I had a same problem and I did the following:

```php
Menu::make('main', function($menu) {
    // ....
    // set a variable $about
    $about = $menu->add(trans('site.about'), ['route' => 'about']);

    // add children items to $about variable
    $about->add('Who we are?', 'who-we-are');

    // contact
    $menu->add(trans('site.contact'),  ['route' => 'contact']);
    // ....
});
```
