### ISSUE TITLE
Pass Associative Array?

### ISSUE THREAD

**Issue by finedesignz** [lavary/laravel-menu#106]
Hi - Your laravel menu package is awesome!

Is there a way to pass in a multi-dimensional associative array to the generator?  Forgive me if this is already documented and I missed it.

EDIT:  What I'm after is the ability to store the menu as a json encoded string in nosql, then retrieve it and render it.

Thank you.

**Comment by lavary** [comment]
This is not currently supported by the package. But that's a good idea. It's helpful to import arrays or even YML files into the Menu builder. 

I'll let you know when it's done. Stay tuned!

I'm glad you liked the package.
