### ISSUE TITLE
I can't create a menu!

### ISSUE THREAD

**Issue by atefeh21** [lavary/laravel-menu#107]
It's going to kill me! I'm a beginner :(
I read all documentation but I don't know where should i define menu, in controller. in middle-ware? and when ever I try to create a menu the Menu class is unidentified  I don't know how to bring the class! like a namespace or use. I just want to create a main menu for my website.
It would be helpful if someone has a small project to show the process completely.
Thank you...

**Comment by lavary** [comment]
You can create a middleware class to define your menus.

To create the middleware, from the terminal, go to your project's root directory and create a middleware class a below:

```bash
php artisan make:middleware MenuMiddleware
```

As a result a middleware class is generated within `app/Http/Middleware` directory named `MenuMiddleware.php`. Open the file and define your menu items in `handle` method of  `MenuMiddleware.php` class:

```php
<?php

namespace App\Http\Middleware;

use Closure;

class MenuMiddleware
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        \Menu::make('MainMenu', function($m) {
            
            $m->add('Item 1', 'item-1-url');
            $m->add('Item 2', 'item-2-url');
            $m->add('Item 3', 'item-3-url');
            
        });

        return $next($request);
    }
}
``` 

Finally add the middleware to `$middleware` property of the `app\Http\Kernel.php` class:

```php
<?php
class Kernel extends HttpKernel
{
    /**
     * The application's global HTTP middleware stack.
     *
     * @var array
     */
    protected $middleware = [
        // ...
        'App\Http\Middleware\MenuMiddleware',

    ];
```


Please note that you need to add a `\` to the `Menu` class, as in ` \Menu::make('MainMenu..., function($m)`. The reason you get the `Class not found` error is because you're calling it from a different namespace. This can be simply resolved by prepending a backslash to the `Menu` facade:

```php
<?php

// ...
 
 \Menu::make('MainMenu', function($m) {
            
            $m->add('Item 1', 'item-1-url');
            $m->add('Item 2', 'item-2-url');
            $m->add('Item 3', 'item-3-url');
            
});

```


Hope that helps.

**Comment by screenager** [comment]
So does the README mention this step ?

Also even with the backslash before the facade call, I still get the "Class 'Menu' not found" error.

On the other side, using `use Lavary\Menu\Menu;` on top, I get following error

> Non-static method Lavary\Menu\Menu::make() should not be called statically, assuming $this from incompatible context

My alias and provider arrays in app.php have references to the package (the Laravel 5.2 style), and I did a composer update and composer dump-autoload.

So what am I missing here?

**Comment by mydansun** [comment]
Hi, @screenager 
please install the ide-helper(https://github.com/barryvdh/laravel-ide-helper)
and use the following command
`php artisan ide-helper:generate`

you can now input `use Menu` on the top of your middleware and use Menu::make()

**Comment by screenager** [comment]
Ok that worked.

Also worth mentioning is that if you want to access the user object in the middleware for checking on roles, the middle should be registered inside the 'web' section of the $middlewareGroups section.
Does that make sense? (I'm not very familiar with the middleware API)

**Comment by newbie2005** [comment]
Any have complete demo how to "middle should be registered inside the 'web' section of the $middlewareGroups section." ?

**Comment by screenager** [comment]
app/Http/Kernel.php :

    /**
     * The application's route middleware groups.
     *
     * @var array
     */
    protected $middlewareGroups = [
      'web' => [
        \App\Http\Middleware\MenuMiddleware::class, 
      ],
    ];


app/Http/Middleware/MenuMiddleware.php : 

    <?php
    
    namespace App\Http\Middleware;
    use Closure;
    use Menu;
    
    class MenuMiddleware
    {
      /**
       * Handle an incoming request.
       *
       * @param  \Illuminate\Http\Request  $request
       * @param  \Closure  $next
       * @return mixed
       */
      public function handle($request, Closure $next) {
        Menu::make('MainNav', function($menu) {
          $menu = $menu->add('Item 1', [
            'route'  => 'myRouteName',
          ]);
          $menu->add('Sub item 1', [
            'route'  => 'otherRouteName',
          ]);
        });
    
        return $next($request);
      }
    }


And in your template file:

    {!! $MainNav->asUl() !!}

Hope it helps

**Comment by kgtu** [comment]
How to add icon for each item?
