### ISSUE TITLE
Check if an item is active (to output someting into the <a> tag)

### ISSUE THREAD

**Issue by ivansammartino** [lavary/laravel-menu#108]
Hello,
I'm using a custom Blade template for rendering menu items
I added the `<li @lm-attrs($item) class="nav-item" @lm-endattrs>` line to "inject" the "active" class where is needed, but I also need to print something inside the `<a>` tag if an item is active
I tried with `@if ($item->active) <span class="selected"></span> @endif`but it dosn't work and I have no clue...
Please, any help? Thank you

**Comment by ivanhalen** [comment]
Got it (if I ain't wrong...): `@if (!empty($item->attributes['class']))<span class="selected"></span>@endif`
Is there a better solution?

**Comment by CrashSensei** [comment]
Sadly if you add any custom classes to your item then your solution will break.
@Macfresno has a safer workaround: `if(strpos($item->attr('class'), 'active'))`

I have also created a patch(https://github.com/lavary/laravel-menu/pull/121) that would allow you to use `$item->isActive` to check

**Comment by dustingraham** [comment]
Patch was merged. Let us know if there is still a problem here.
