### ISSUE TITLE
Is using middleware good for performance?

### ISSUE THREAD

**Issue by notflip** [lavary/laravel-menu#110]
Isn't there another way of loading these? Correct me if I'm wrong but isn't always loading them using middleware bad for performance? Thank you!

**Comment by dennisoderwald** [comment]
+1

**Comment by abishekrsrikaanth** [comment]
why not set it up as a named middleware and apply it only to needed routes?

**Comment by dustingraham** [comment]
Closing to continue the discussion in 111.
