### ISSUE TITLE
Call to undefined method Lavary\Menu\Link::prepend()

### ISSUE THREAD

**Issue by dennisoderwald** [lavary/laravel-menu#112]
I cannot use the append or prepend function.

``` php
$menu->add(trans('navigation.dashboard'), route('account.index.get'))->nickname('account');
$menu->account->link->attr(['class' => 'font-green']);
$menu->account->link->prepend('<i class="icon-settings"></i>');
```

**Comment by lavary** [comment]
The link object doesn't have `append` or `prepend` method. You may call them against the item object itself.

---
Closing the issue. please feel free to reopen if you have any more questions.

Thanks
