### ISSUE TITLE
can't create group

### ISSUE THREAD

**Issue by snopein** [lavary/laravel-menu#115]
i want create Nested Groups 
i put the example code 

```
<?php
Menu::make('MyNavBar', function($menu){

    // ...

    $menu->group(array('prefix' => 'pages', 'data-info' => 'test'), function($m){

        $m->add('About', 'about');

        $m->group(array('prefix' => 'about', 'data-role' => 'navigation'), function($a){

            $a->add('Who we are', 'who-we-are?');
            $a->add('What we do?', 'what-we-do');
            $a->add('Our Goals', 'our-goals');
        });
    });

});
?>
```

and render it 

but i get this view

```
<ul class="navigation navigation-main navigation-accordion">
<li data-info="test"><a href="http://localhost:8000/pages/about">About</a></li>
<li data-info="test" data-role="navigation"><a href="http://localhost:8000/pages/about/who-we-are?">Who we are</a></li>
<li data-info="test" data-role="navigation"><a href="http://localhost:8000/pages/about/what-we-do">What we do?</a></li>
<li data-info="test" data-role="navigation"><a href="http://localhost:8000/pages/about/our-goals">Our Goals</a></li>
</ul>
```

**Comment by snopein** [comment]
if i do this 
```
Menu::make('MyNavBar', function($menu){

    // ...

    $menu->group(array('prefix' => 'pages', 'data-info' => 'test'), function($menu){

        $menu->add('About', 'about');

        $menu->about->group(['prefix' => 'about','parent'=>$menu->about->id], function($menu){

            $menu->about->add('Who we are', 'who-we-are?');
            $menu->about->add('What we do?', 'what-we-do');
            $menu->about->add('Our Goals', 'our-goals');
        });
    });

});
```
it's work

i get view 
<ul class="navigation navigation-main navigation-accordion">
<li data-info="test" class="active"><a href="http://localhost:8000/pages/about" class="has-ul">About</a>
<ul class="hidden-ul" style="display: block;">
<li data-info="test"><a href="http://localhost:8000/pages/about/who-we-are?">Who we are</a></li><li data-info="test"><a href="http://localhost:8000/pages/about/what-we-do">What we do?</a></li><li data-info="test"><a href="http://localhost:8000/pages/about/our-goals">Our Goals</a></li>
</ul>
</li>
</ul>

**Comment by malyusha** [comment]
@snopein I have the same problem. I guess it's happening because when you call `group` method on menu it passes global whole menu's builder instance to callback instead of item's builder instance. So, it's probably bug.

**Comment by lavary** [comment]
This has been fixed in the previous release.

----
Closing the issue. Please feel free if you have any more questions regarding the issue.

Thanks.
