### ISSUE TITLE
menu localization issue

### ISSUE THREAD

**Issue by yizhihou2** [lavary/laravel-menu#118]
Hi,

I was trying to code in this way,

$m->add(trans('navigation.browse'), array('route'  => 'browse.main'));

and got an error saying, "Call to a member function add() on a non-object". Is there a way for laravel-menu to support different languages with Laravel's localization feature?

Thanks.

**Comment by Landish** [comment]
I'm using the `trans` function as well and it works as expected.

According to your error message the `$m` is not an object.

Can you post the whole code of how you're creating menu and adding items?
