### ISSUE TITLE
Question/Bug Can not push item into menu from seperate middleware.

### ISSUE THREAD

**Issue by nat-** [lavary/laravel-menu#120]
I am trying to add an item to a menu from different middleware but having no luck.

So to setup I have a menu that only builds when I have a student key available so I am building it in a 
`

```
    \Route::bind('student', function($id)
    {

        $student = \Student\Student::findOrFail($id);
            \Menu::make('Student_Tabs', function($menu) use($student) {

                   $menu->add('Basic Details', route('student.show', $student->getKey() ) );) );

        });
        return $student;
    });
```

`

Then I have another peice of middleware that needs to load in a menu object seperately 
so I am using 
`
    \Menu::get('Student_Tabs')->add('Menu_item', "what/evs");
`

But this wont load into the menu.
I can return the menu object with 
`
dd(\Menu::get())
`
And can see every other menu object.

**Comment by dustingraham** [comment]
Howdy,

This problem should be resolved. Running subsequent `Menu::make()` with the same name will now give you the same $menu object that you can add to.

Re-open if you still need help.

Thanks,
-Dustin
