### ISSUE TITLE
Menus in database 

### ISSUE THREAD

**Issue by reypm** [lavary/laravel-menu#124]
It's possible to create menu items on database and then load from there? I think the only way your library provide us to use menus is by defining all of them in a file after if I need to add a new menu I will need to go to that file and add the new item. So could menu items be saved and loaded from a DB table? How?

**Comment by lavary** [comment]
It's possible to have your menu properties in a database. The answer to your second question will depend on how you're going to save the menu-related data in your database. 

Anyway, shouldn't be too much complicated: you'll just need to fetch the data from a database, then iterate over the fetched result and create the items using Laravel Menu's interface.

Good luck.

**Comment by reypm** [comment]
Perfect @lavary I will close the issue, if I get any other problem I will let you know

**Comment by zendzo** [comment]
@reypm do you success implement your menu with database integration? can you please provide the tutorial please?
