### ISSUE TITLE
where no $item->isActive() method?

### ISSUE THREAD

**Issue by fykyx521** [lavary/laravel-menu#127]
like $item->isActive() 'current' @endif
`<div class="info-left ng-scope" ui-view="left">
    <div class="subNavBox  ng-scope">
        @foreach($items as $item)
            <div class="subNav @if $item->isActive() 'current' @endif"> <i class="icon-sub icon1"></i><a href="#">{{$item->title}}</a></div>
            @if($item->hasChildren())
            <ul class="navContent" style="">
                @foreach($item->children() as $child)
                    <li>
                        <a href="{{$child->url}}">{{$child->title}}</a>
                    </li>
                @endforeach
            </ul>
            @endif
        @endforeach
    </div>
</div>`

**Comment by cyberdog478** [comment]
Remove the ()

Example:
` <li @if($item->isActive) class="current" @endif >`
