### ISSUE TITLE
How to deal with this URLs pattern?

### ISSUE THREAD

**Issue by reefki** [lavary/laravel-menu#128]
I have following URLs

```
http://mysite.com/users/
http://mysite.com/users/create
http://mysite.com/users/{id}/edit

http://mysite.com/users/roles
http://mysite.com/users/roles/create
http://mysite.com/users/roles/{id}/edit
```

And here is my menu items:

```
$menu->add('Users', 'users');
$menu->add('Roles', 'users/roles');
```

How to prevent `Users` menu item being activated when I visiting `Roles`?

**Comment by dustingraham** [comment]
Hi. This might be old behavior. Can you confirm whether this is still a problem? I tested with something similar and it only set the specific item to active. When on users/roles only Roles was active. When on users, only Users was active.

Thanks.
