### ISSUE TITLE
Adding special li class to a ul

### ISSUE THREAD

**Issue by basenetpaolo** [lavary/laravel-menu#133]
Hey,

I'm using this code which is working great, but I need to add a class of "navOnScroll" to my li. please can you help?

{!! $Frontend->asUl( array('class' => 'nav navbar-nav navbar-right') ) !!}

I couldn't see it documented anywhere.

Thanks,
Paolo

**Comment by idealley** [comment]
You could add the class like this:
    $menu->add('Your menu', array('url' => 'the-url', 'class' => 'horizontal'));
