### ISSUE TITLE
Parse some data to route from views in menu

### ISSUE THREAD

**Issue by safoorsafdar** [lavary/laravel-menu#138]
I need to parse some dynamic data to menu like `id` to parse in route.

**Comment by safoorsafdar** [comment]
``` php
Menu::make('tenant.account.detail_nav', function ($menu) {
            $menu->add('Summary',
                array(
                    'route' => array('detail/account', 'id' => 148),
                ))->data('permission', 'view-account');
        });
//and my views

{!!  Menu::get('tenant.account.detail_nav')->filter(function ($item) {
                        return access()->can($item->data('permission'));
                })->asUl() !!}

```

**Comment by safoorsafdar** [comment]
There is any mechanism available to parse something to menu initialization from views and get parsed data `$menu` closure.

Thanks in advance.

**Comment by Sarav-S** [comment]
@safoorsafdar By "I need to parse" do you actually mean to pass $id variable to function?

**Comment by safoorsafdar** [comment]
@Sarav-S yes, i have a id which is only available in views, the way i'm looking for, is to parse that view specific id to menu to parse in `route`.

**Comment by xnetmexico** [comment]
We solved it changing the Vendor Files (not a good practice), we changed /vendor/lavary/laravel-menu/src/Lavary/Menu/Menu.php to accept a parameter $prm, 
then we sent over the paremeter while creating the menu.

HTH

Rodrigo O
Xnet.mx

Around Line 29 of Menu.php
	public function make($name, $callback, $prm=1) //se agrego $prm=1 rol 2016 by xnet.mx
	{
		if(is_callable($callback))
		{
			
			$menu = new Builder($name, $this->loadConf($name));
			
			// Registering the items
			call_user_func($callback, $menu , $prm);  //se agrego $prm=1 rol 2016 by xnet.mx
			
			// Storing each menu instance in the collection
			$this->collection->put($name, $menu);
			
			// Make the instance available in all views
			\View::share($name, $menu);

			return $menu;
		}
	}



// Example usage
$prameter_to_send=Auth::id();	

	Menu::make('mprofile', function($menu3,$prm){
		//PARAMETER IS USED BELOW
$users = DB::table('MENUOPTIONS')->where('ROLE','=', $prm)->orderBy('ORDEN', 'asc')->get();	 
foreach ($users as $user)
	
{
	$enlace = $user->LINK;
	$cont = $user->CONTROLLERNAME;
	$tl=$user->TITULO;
	$menu3->add($tl, array('url' =>  $enlace,'title' => 'Ok'));
	
}
    
}, $prameter_to_send  );	 //PARAMETER IS SENT HERE

**Comment by dustingraham** [comment]
Can you create your menu in the controller instead? Or, just add the new elements in the controller? I know you said "parse the data from the view" but I suspect you should have access to that data from the controller, no?

In some `OrderController@show` method.

    public function show($id) {
        $order = Orders::find($id);
        \Menu::make('MyNavBar', function ($menu) use($id) {
            $menu->add('orders', array('action' => array('OrderController@show', 'id' => $id)));
        });
        return view('order.show')->with('order', $order);
    }

Please re-open this if you'd like to discuss further.
