### ISSUE TITLE
No `href` for anchors

### ISSUE THREAD

**Issue by arkhi** [lavary/laravel-menu#141]
I’ve been looking in other issues and some code to no avail.

I would like to keep styles consistent without having a link to `#`, as this means more code.

Is it possible to have anchors not being links?

``` html
<ul>
    <li>
        <a></a>
        <ul>
            <li><a href="…"></a></li>
            <li><a href="…"></a></li>
        </ul>
    </li>
</ul>
```

instead of 

``` html
<ul>
    <li>
        <a href="#"></a>
        <ul>
            <li><a href="…"></a></li>
            <li><a href="…"></a></li>
        </ul>
    </li>
</ul>
```

**Comment by sartatpdev999** [comment]
#172 can solve it

**Comment by dustingraham** [comment]
`$menu->add('Example', null);` with the latest release will now omit the href part.
