### ISSUE TITLE
Breaking Changes in 8eb8571e14cd91fc354a63df874d9cd193a18bc3

### ISSUE THREAD

**Issue by lukepolo** [lavary/laravel-menu#143]
If your view composer loads twice (can happen) , you will duplicate your menus

A solution outside the package is to make the view composer a singleton and check to see if its already been loaded.

**Comment by ecoreng** [comment]
I am also experiencing this.

**Comment by dustingraham** [comment]
Sorry about that. The change was valuable, but it wasn't immediately obvious the problem you would encounter!

You can now use `Menu::makeOnce()` or check with `Menu::exists()`
