### ISSUE TITLE
How to display dividers/make active on looped out menu?

### ISSUE THREAD

**Issue by allw1994** [lavary/laravel-menu#147]
Hi,

I have followed your guide in order to create bootstrap compatible menus, but i want to be able to add a divider between dropdown menu items, how do i do that? can i test for it using something like:

```
@foreach($items as $item)
  <li @if($item->hasChildren()) class="dropdown" @endif>
    <a href="{!! $item->url() !!}" @if($item->hasChildren()) class="dropdown-toggle" data-toggle="dropdown" @endif>{!! $item->title !!} @if($item->hasChildren()) <span class="caret"></span> @endif </a>
    @if($item->hasChildren())
      <ul class="dropdown-menu">
         @include('menu-items', array('items' => $item->children()))
      </ul>
    @endif
    @if($item->isdivider())
      <ul class="divider"></ul>
    @endif
  </li>
@endforeach
```

Thanks for the help!

**Comment by lavary** [comment]
You can simply check if the item has a divider:

```php
@foreach($items as $item)
  <li @if($item->hasChildren()) class="dropdown" @endif data-test="test">
      <a href="{!! $item->url() !!}">{!! $item->title !!} </a>
      @if($item->hasChildren())
        <ul class="dropdown-menu">
              @include('custom-menu-items', array('items' => $item->children()))
        </ul> 
      @endif
  </li>
@if ($item->divider)
 <li class="divider"></li>
@endif
@endforeach
```

**Comment by allw1994** [comment]
Hi,

Firstly $item->divider throws an error i believe $item->divide works as intended though, but it's dividing every single menu item, i am only looking for it to divide certain menu entries? is this possible?

**Comment by lavary** [comment]
What error do you get when trying to access `$item->divider` ?

**Comment by lavary** [comment]
There's no such method as `divider()`; Instead you need to call `divide()`.
`divider` is a property of the item. Please take a closer look at my previous answer.

**Comment by allw1994** [comment]
which is what i am saying, if you look closely at what you put you wrote @if ($item->divider) which is throwing the error, but without changing that to divide i get no separators. unfortunately when that line of code is working it separates all the menu items which is not what i am looking for

**Comment by lavary** [comment]
Can I see your exact code?
According to your last reply you get `Call to undefined method Lavary\Menu\Item::divider()` which is raised when a non-existing **method** is called, whereas `$item->divider` (without parenthesis) is a reference to a property of the class.

**Comment by allw1994** [comment]
Exact code:

```
namespace App\Http\Middleware;

use Closure;
use Menu;

class NavMenu
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
      Menu::make('NavMenu', function($menu){
        //$menu->add('Home'); //already added on menu.blade

        $menu->add('Forum', 'forum')->active('forum/*');
        $menu->forum->add('Newest Posts', 'forum');
        $menu->forum->add('Trending', 'forum/trending_posts');
        $menu->forum->divide();
        $menu->forum->add('Create Post', 'forum/create_post');
        $menu->forum->add('Your Posts', 'forum/your_posts');


        $menu->add('Chat', 'chat');

        $menu->add('Messages', 'messages')->active('messages/*');
        $menu->messages->add('Unread', 'messages/unread');
        $menu->messages->add('Read', 'messages/read');
        $menu->messages->add('Sent', 'messages/sent');
        $menu->messages->divide();
        $menu->messages->add('All', 'messages');

      });
      return $next($request);
    }
}
```

**Comment by allw1994** [comment]
dunno what I did to fix it but i have managed to get it to work, thanks for all the help!
