### ISSUE TITLE
How to cache?

### ISSUE THREAD

**Issue by eleftrik** [lavary/laravel-menu#149]
Is it possible to cache a menu?

I store my menu(s) on a database table. I read the items / sub-items associated to a given menu, then I "build" it using the methods you provide with your package.
Once cached, it would be nice to avoid reading from menu and skipping the building part.
I would like to do something similar:

```
// If my menu has already been cached...
Menu::set('my.menu.name', Cache::get('my.menu.name'));
```

Is it possible?

Thank you

**Comment by eleftrik** [comment]
@lavary Can you help me? Thank you

**Comment by lavary** [comment]
Sorry for the extremely delayed response.

Currently, it's caching is not provided with the package. However, I'll consider this one in the next release. Meanwhile, you may use your own caching mechanism.

Stay tuned.


----------
Closing the issue. Please feel free to reopen if you have any more questions. 

Thanks.

**Comment by eleftrik** [comment]
Hi @lavary, I tried to use my own caching mechanism, but once I read from the cache, I don't know how to set my menu, how to assign what I've cached.

Thank for your feedback

**Comment by Vmadmax** [comment]
Any progress on this?

**Comment by dustingraham** [comment]
I don't anticipate any caching being added to this component.

Laravel already has a pretty good handle on caching. Or you can use something like https://laravel-news.com/page-cache

I don't think caching Laravel Menu directly is really going to solve website bottlenecks.
