### ISSUE TITLE
menu in bootstrap

### ISSUE THREAD

**Issue by BO55** [lavary/laravel-menu#150]
i'm a beginner, please help. i'm trying to use this menu for bootstrap. where do i have to include the partial view as told in the documentation.
thanks...

**Comment by lavary** [comment]
The partial code is already included with the package. You only need to write the parts that has been explained in the documentation, [Menu as Bootstrap 3 Navbar](https://github.com/lavary/laravel-menu#menu-as-bootstrap-3-navbar) section.

Closing the issue. Please feel free to reopen if you have any more questions.

Thanks.
