### ISSUE TITLE
UrlGenerator  with Anchor #

### ISSUE THREAD

**Issue by link08** [lavary/laravel-menu#151]
Hello,
I've tried to build a menu navigation with both anchors and routing urls, but the root path is always included inside each url.

With this code:
```
\Menu::make('publicMenu', function($menu){
                    $menu->add('service', '#service');
                    $menu->add('contacts', #contacts');
                    $menu->add('reserved area', ['route' => 'reserved.home'])->active('reserved/*');
                });
```

I want this:
```
<li>
  <a href="#services">services</a>
</li>
<li>
  <a href="#contacts">contacts</a>
</li>
<li>
  <a href="http://mydomain.com/reserved">reserved area</a>
</li>
```

But i got this:
```
<li>
  <a href="http://mydomain.com/#services">services</a>
</li>
<li>
  <a href="http://mydomain.com/#contacts">contacts</a>
</li>
<li>
  <a href="http://mydomain.com/reserved">reserved area</a>
</li>
```

I saw that the Laravel UrlGenerator doesn't add the root path if the URL start with:
'#', '//', 'mailto:', 'tel:', 'http://', 'https://' return itself.

In your Builder, in the line:
https://github.com/lavary/laravel-menu/blob/master/src/Lavary/Menu/Builder.php#L387

with or without the $prefix, the '/' character is always being added. Is it possibile remove the '/' if the prefix is not set?

Loris.

**Comment by lavary** [comment]
At the moment, all the URLs are prefixed with the site's domain (unfortunately). However, you can force your URIs by using `href()` method of each item's link object.

```php
<?php
\Menu::make('publicMenu', function($menu){
    $menu->add('service')->link->href('#service');
    $menu->add('contacts')->link->href('#contacts');
    $menu->add('reserved area', ['route' => 'reserved.home'])->active('reserved/*');
});
```

This issue has been solved in the next major release, which is coming out next week. Until then you may  use the the `href()` method on the link object.

**Comment by freezy-sk** [comment]
@lavary link is still force prefixed with `/`. Was there some problem why it wasn't released in that major release?
