### ISSUE TITLE
Add menu item before a specific menu item

### ISSUE THREAD

**Issue by ttimot24** [lavary/laravel-menu#160]
I would like to add a menu item before a specific menu item. 
Is there a way for that?

If not is there a chance that you will add this feature later?

**Comment by lavary** [comment]
If you're writing the code, you can obviously define your menus wherever you want.

If you're loading your data from a database you can use the ordering feature. Then order your items based on the order value.

If this works for you, you may take a look at the documentation about ordering. Otherwise, let me know. We'll find a way.

Thanks.

**Comment by ttimot24** [comment]
It's for a plugin system. In the plugin I can only define the menu item I would use for correlate.

**Comment by dustingraham** [comment]
`$menu->all()` is a laravel collection. So you can do all the normal things to it such as iterating via each.

https://laravel.com/docs/5.5/collections#method-each

Once you find the key for the target position you can splice it in. For example.

        \Menu::make('MyNavBar', function ($menu) {
            $menu->add('Home');
            $menu->add('About', 'about');
            $menu->add('Services', 'services');
            $menu->add('Contact', 'contact');
        });    
        
        /** @var \Lavary\Menu\Builder $builder */
        $builder = \Menu::get('MyNavBar');
    
        /** @var \Illuminate\Support\Collection $collection */
        $collection = $builder->all();
        
        $target = null;
        $collection->each(function($item, $key) use (&$target) {
            if ($item->title == 'About') {
                $target = $key;
                // Found it, break out.
                return false;
            }
        });
    
        $item = new Item($builder, 'myid1', 'Inserted', ['url' => 'follow']);
        // Insert before the found element. $target+1 to insert after.
        $collection->splice($target, 0, [$item]);

Then the menu would be `Home | Inserted | About | Services | Contact`

Let me know if this helps, or if you have any other questions.
