### ISSUE TITLE
Divider with text

### ISSUE THREAD

**Issue by pedrosalpr** [lavary/laravel-menu#161]
Hi! I would like to know how I do to build the menu with the following features:

`<li class="header"> HEADER </li>`

It is of type divider, however the divider does not accept text.

I think I could modify the divider to accept the text.

I'm using [adminLTE](https://www.almsaeedstudio.com/themes/AdminLTE/pages/UI/general.html). And if you repair in the menu sidebar there is the text "Main Navigation", which is this type of header.

Thank you.

**Comment by lavary** [comment]
I'll include this feature in the next release.

Stay tuned!
