### ISSUE TITLE
Class 'Lavary\Menu\Facade' not found laravel 5.4

### ISSUE THREAD

**Issue by UriLucioWald** [lavary/laravel-menu#165]
Hi,
When using Laravel5.3 it worked smooth,
Now when I am using Laravel 5.4 I am getting the following error Class 'Lavary\Menu\Facade' not found laravel 5.4
`at HandleExceptions->handleError(2, 'Class \'Lavary\\Menu\\Facade\' not found', '/var/www/localhost/htdocs/test2/haigui2/vendor/laravel/framework/src/Illuminate/Foundation/AliasLoader.php', 79, array('alias' => 'Menu'))`
By the way I can see the Facade.php under vendor\lavary\laravel-menu\src\Lavary\Menu 
In the config/app.php I did added in the aliases
'Menu' => 'Lavary\Menu\Facade',
Any idea ?

**Comment by lavary** [comment]
Where do you use the Menu service? 

Since your code is in a different namespace than menu, you may be missing a "\" before `Menu`.

**Comment by UriLucioWald** [comment]
Hi,
Thanks for the quick reply
I use it in my middleware in the way you specify.
`    private function makeMenu(){
        \Menu::make('MyNavBar', function($menu){
            $menu->add('Home');
            $menu->add('Lessons', 'lessons');
        });
    }`
The error doesn't say that Class 'Menu' not found (That will happen if I remove the alias)
but says that he doesn't understand the alias 'Menu' => 'Lavary\Menu\Facade',.
after  `php artisan vendor:publish` should I do more things related ?
In 5.3 it worked with no problem

**Comment by UriLucioWald** [comment]
Hi,
In the 4th time I created a new Laravel project it seems to work.
No idea why it didn't work before

**Comment by dustingraham** [comment]
Glad it is working.

**Comment by spaceblock** [comment]
Hi, not work with this problem
