### ISSUE TITLE
when make subitem ,use chinese for menu name ->get error

### ISSUE THREAD

**Issue by ufowiner** [lavary/laravel-menu#167]
Menu::make('tmenu', function($menu){

            $menu->add("测试",'test');

            //always echo " all to a member function add() on null "
            $menu->get("测试")->add('测试2','test/test2');
           or
            $menu->item("测试")->add('测试2','test/test2');

**Comment by lavary** [comment]
If understood your problem correctly, the menu builder turns your titles into ASCII characters (That's why you cannot get the item's nicknames)

You may either put your item's instance in a variable or explicitly specify its nickname:

```php
<?php

$item = $menu->add("测试",'test');
$item->add('测试2','test/test2');

// OR

$menu->add("测试",'test')->nickname('itemNickname');
$menu->get('itemNickname')->add('测试2','test/test2');

```

**Comment by ufowiner** [comment]
thanks  for you help  solved
