### ISSUE TITLE
No active link detection if using https

### ISSUE THREAD

**Issue by nicozimmermann94** [lavary/laravel-menu#168]
Hey there,

everything works fine on my local dev machine using http. But as soon I deploy to my https test server, the active link detection stops working and I have to do `->active('url')` everywhere. Is this intended behaviour?

`$support = $menu->add('Support', 'account/support')->data('icon', 'life-ring');
            $support->active('account/support/*');`

**Comment by HejVkt** [comment]
i've same problem. It works only for route, example:

$menu->about->add('document', ['route' => ['docs']]);

but

$menu->about->add('docs', 'pages/docs'); 
doesn't work

**Comment by HejVkt** [comment]
you need to replace your example to
 
 $support = $menu->add('Support', ['url'=>'account/support', 'secure'=> true)->data('icon', 'life-ring');

**Comment by nicozimmermann94** [comment]
@HejVkt Well this is not what I intended because now it forces https links to be generated, but my local dev machine does not use https.

**Comment by HejVkt** [comment]
you can use flag in your .env like APP_HTTPS=false on dev and APP_HTTPS=false on production server. And you can use it in your code like this:

$secure = env('APP_HTTPS');
$support = $menu->add('Support', ['url'=>'account/support', 'secure'=> $secure] )->data('icon', 'life-ring');

**Comment by nicozimmermann94** [comment]
well yes that would work, thank you for the input. but that does not really 'solve' the initial problem or am I thinking wrong?

**Comment by dustingraham** [comment]
Closing this as I think #131 will solve the problem. Please re-open if not.
