### ISSUE TITLE
Nested resource parameter

### ISSUE THREAD

**Issue by duongtdvn** [lavary/laravel-menu#171]
I am currently creating a menu with nested resource parameter like this:

```bash
Product:
http://domain.com/orders/{orderid}/items
Invoice:
http://domain.com/orders/{orderid}/invoices
...
```

So is there anyway to pass the `orderid` parameter while create the menu?

**Comment by dustingraham** [comment]
See: https://github.com/lavary/laravel-menu#controller-actions

`$menu->add('services', array('action' => array('ServicesController@index', 'id' => 12)));`

Let me know if you still need help.

**Comment by duongtdvn** [comment]
@dustingraham I see, but how do you pass the `id` parameter as variable because when i provide like so:

```php
$menu->add('orders', array('action' => array('OrderController@show', 'id' => $order->id)));
```

it then throw an error `Undefined variable: order`.

**Comment by dustingraham** [comment]
You can do something like this.

```
        \Menu::make('MyNavBar', function ($menu) use($order) {
            $menu->add('orders', array('action' => array('OrderController@show', 'id' => $order->id)));
```

**Comment by duongtdvn** [comment]
How do you send the `order` parameter from Controller to Middleware to use it in the function like that?

**Comment by dustingraham** [comment]
You will need to decide how you want to organize your code in the big picture.

However, I would suggest that you could either build the entire menu in the controller. Or, you could build just this piece of the menu in the controller.

With 1.6+ you can call make twice on the same menu.

    public function handle($request, Closure $next)
    {
        \Menu::make('MyNavBar', function ($menu) {
            $menu->add('Home');
            $menu->add('About', 'about');
            $menu->add('Services', 'services');
            $menu->add('Contact', 'contact');
        });

        return $next($request);
    }

Then in your controller

    public function show($id)
    {
        $order = Orders::find($id);
        \Menu::make('MyNavBar', function ($menu) use($id) {
            $menu->add('orders', array('action' => array('OrderController@show', 'id' => $order->id)));
        });
        return view('order.show')->with('order', $order);
    }

There is no requirement to initialize the menu in middleware, it is just convenient usually.

**Comment by duongtdvn** [comment]
Thank you, I was also think about making the menu in Controller method, but make the menu twice is great, so i can push menu item from controller to middleware class!

**Comment by dustingraham** [comment]
It isn't technically pushing into middleware. It's adding on after middleware has executed.

But yes, give that a try. Hope it helps. :)
