### ISSUE TITLE
5.4 error by composer require lavary/laravel-menu

### ISSUE THREAD

**Issue by nousename** [lavary/laravel-menu#173]
Getting the following when trying to install

Using version ^1.6 for lavary/laravel-menu
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing lavary/laravel-menu (v1.6.1): Downloading (100%)         
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize

                                                         
  [Symfony\Component\Debug\Exception\FatalThrowableError]  
  Class 'Menu' not found                                   
                                                           

Script php artisan optimize handling the post-update-cmd event returned with error code 1

Installation failed, reverting ./composer.json to its original content.

Any suggestions?

**Comment by fulopattila122** [comment]
The error shouldn't show up, but you probably can fix it by adding `'Menu' => 'Lavary\Menu\Facade'` to the `$aliases` array in `config/app.php`:

```
<?php

'aliases' => [

    'App'       => Illuminate\Support\Facades\App::class,
    'Artisan'   => Illuminate\Support\Facades\Artisan::class,
    ...
    'Menu'       => 'Lavary\Menu\Facade',

],
?>
```

**Comment by jundycosmod** [comment]
I'm having the same error even after adding 
`<?php

'aliases' => [

    'App'       => Illuminate\Support\Facades\App::class,
    'Artisan'   => Illuminate\Support\Facades\Artisan::class,
    ...
    'Menu'       => 'Lavary\Menu\Facade',

],
?>`

**Comment by dustingraham** [comment]
Is this still a problem? What version of laravel?
