### ISSUE TITLE
Problems with repetitions.

### ISSUE THREAD

**Issue by jmmendozamix** [lavary/laravel-menu#174]
Hello everyone.

I am building a dynamic Bootstrap menu and it works fine but when the menu has more than one child, the parent is repeated for each child. I would like help to solve the problem.

I have created a "post" table that does the work of all type of content identifying each type with a field called with the same name "type". The pages are identified with the field "type = page". The idea is similar to the "post_type" of WordPress. The menu works fine but i can not figure out how to make the menu without building a menu builder. What i want is to be simple and to be manipulated only by changing the checkbox "in_menu" true | False, "order" 0 to 9 and parent = any page. I do not write well in English but i imagine they understand me.

The code I am using is the following:

```
Menu::make( 'frontendMenu', function( $menu ) {
	$home      = App\Post::where( 'type', 'page' )->where( 'status', 'publish' )->where( 'template', 'home' )->first();

	$childrens = App\Post::where( 'status', 'publish' )->where( 'parent', '>', 0 )->where( 'menu', 1 )->orderBy( 'menu_order' )->get();

	$pages     = App\Post::where( 'type', 'page' )->where( 'status', 'publish' )->where( 'template', 'default' )->where( 'menu', 1 )->where( 'parent', 0 )->orderBy( 'menu_order' )->get();

	if ( $home )
		$home = $menu->add( $home->title, $home->slug );

	if ( $pages ) {
		foreach ( $pages as $page ) {
			$r = $menu->add( $page->title, $page->slug );
			if ( count( $childrens ) > 0 ) {
				$r->attr(['class' => 'dropdown'])->link->href('javascript:void(0);')->attr(['class' => 'dropdown-toggle', 'data-hover' => 'dropdown', 'data-toggle' => 'dropdown']);
				foreach ( $childrens as $child ) {
					if ( $child->parent === $page->id ) {
						$r->add( $page->title, $page->slug );
						$r->add( $child->title, $child->slug );
					}
				}
			}
		}
	}
});
```

The result is as follows:

```
<ul class="nav navbar-nav">
	<li class="active"><a href="http://www.project.dev/inicio">Página principal</a> </li>
	<li class="dropdown"><a class="dropdown-toggle" data-hover="dropdown" data-toggle="dropdown" href="javascript:void(0);">Productos</a> </li>
	<li class="dropdown"><a class="dropdown-toggle" data-hover="dropdown" data-toggle="dropdown" href="javascript:void(0);">Información</a>
		<ul class="dropdown-menu">
			<li><a href="http://www.project.dev/informacion">Información</a> </li>
			<li><a href="http://www.project.dev/terminos-y-condiciones">Términos y condiciones</a> </li>

			<- this is the problem -> 

			<li><a href="http://www.project.dev/informacion">Información</a> </li>
			
			<- this is the problem ->

			<li><a href="http://www.project.dev/politicas-de-privacidad">Políticas de privacidad</a> </li>
		</ul>
	</li>
	<li class="dropdown"><a class="dropdown-toggle" data-hover="dropdown" data-toggle="dropdown" href="javascript:void(0);">Noticias</a> </li>
	<li class="dropdown"><a class="dropdown-toggle" data-hover="dropdown" data-toggle="dropdown" href="javascript:void(0);">Nosotros</a> </li>
</ul>
```

Thank you very much!!

**Comment by dustingraham** [comment]
Are you still having a problem?

**Comment by dustingraham** [comment]
The deepest $r->add( $page->title, $page->slug ); is not necessary.

If you want Informacion to be repeated in the submenu, then perhaps:

				foreach ( $childrens as $i => $child ) {
					if ( $child->parent === $page->id ) {
						if ($i == 0) $r->add( $page->title, $page->slug );
						$r->add( $child->title, $child->slug );
					}
				}

So that it only adds the duplicate Informacion once for the submenu. Or you could even put it outside of the foreach loop.

Going to close since this is an old issue. Please re-open if you'd like more help.
