### ISSUE TITLE
Left menu dependent on top menu item

### ISSUE THREAD

**Issue by fjoho** [lavary/laravel-menu#179]
Is there a solution for having a top menu that triggers a left menu? Each top menu items triggers different left menus. And while navigating the left menu keeping the top menu item active.

**Comment by dustingraham** [comment]
Can you provide an example of the "top" and "left" menus?

Active menu items are determined based on the URL, so if the URL changes, they should both use the same logic to determine which is active.

**Comment by dustingraham** [comment]
Please re-open with more details if you still need help.
