### ISSUE TITLE
Unable to use custom menu template

### ISSUE THREAD

**Issue by razzul** [lavary/laravel-menu#181]
I was trying to over the menu temple using a custom template as per my design need from `/resources/views/menus.blade.php`

Here is my `/config/laravel-menu/views.php`
```php
<?php

return array(
	'bootstrap-items' => 'views.menus'
);
```

**Comment by medeirosrafael** [comment]
Are you using: @include(config('laravel-menu.views.bootstrap-items'), array('items' => $mainNav->roots()))
to render your menu?

**Comment by dustingraham** [comment]
@razzul Please let us know if this is still a problem.
