### ISSUE TITLE
Can't access menu item because of its name format

### ISSUE THREAD

**Issue by mvww11** [lavary/laravel-menu#183]
Hello!
i'm trying to create sub items:
```
$m->add('Revisão de Exercícios', ['url' => 'revisar/exercicios']);
$m->item('Revisão de Exercícios')->add('Sem Aula', 'revisar/exercicios?sem-aula');
```
But I'm getting the following error:
`Call to a member function add() on null`

I guess it can't find the item 'Revisão de Exercícios' because of its format name. Just to check it out, I tried the following and it works fine:
```
$m->add('about', ['url' => 'revisar/exercicios']);
$m->item('about')->add('Sem Aula', 'revisar/exercicios?sem-aula');
```

Can I create the subitem while maintaining the name format?

Thanks!

**Comment by lavary** [comment]
The `add()` method, automatically turns UTF-8 characters into their ASCII equivalent. Then, transforms it into camel case, and uses it as the item's key. 

Knowing this, your item's key will become: `RevisaoDeExercicios`. To access it:

```php
<?php

// ...

$m->RevisaoDeExercicios->add('Sem Aula', 'revisar/exercicios?sem-aula');

// Or

$m->item('RevisaoDeExercicios')->add('Sem Aula', 'revisar/exercicios?sem-aula');

// ...

```

Alternatively, you can store your item's object (Revisão de Exercícios) in a variable for later reference, like this:

```php
<?php

// ...

$RevisaoDeExercicios = $m->add('Revisão de Exercícios', ['url' => 'revisar/exercicios']);
$RevisaoDeExercicios->add('Sem Aula', 'revisar/exercicios?sem-aula');

// ...
```

**Comment by mvww11** [comment]
@lavary Thanks for the fast reply! It works fine :)
