### ISSUE TITLE
How to change UL class for submenus?

### ISSUE THREAD

**Issue by kgtu** [lavary/laravel-menu#187]
We can change class for main UL:

{!! $MenuName->asUl( array('class' => 'first-level-ul'), array('class' => 'second-level-ul')  ) !!}

How to change class for ALL other ULs?

**Comment by kgtu** [comment]
You have to fix file Builder.php, line 528
from
				$items .= $this->render($type, $item->id);
to
				$items .= $this->render($type, $item->id, self::attributes($childrenAttributes));

**Comment by dustingraham** [comment]
Good find! Fixed.
