### ISSUE TITLE
Option for not adding an anchor tag

### ISSUE THREAD

**Issue by sanpakyou027** [lavary/laravel-menu#189]
Is there an option for not automatic adding an anchor tag?
```
Menu::make("Menu",function($menu){
	$menu->add("Application",
		[
			"class" => "header"
		]
	);
	$menu->add('Home', 
		[
			"route" => "Home",
			"class" => "treeview"
		]
	);
});
```

ex. output
```
<ul>
<li class="header">Application</li>
<li><a href="home">Documentation</a></li>
<ul>
```

**Comment by dustingraham** [comment]
Howdy. `raw` will omit the `<a>` tag completely. Or, `'url' => null,` will create an `<a>` tag without an href attribute.

    \Menu::make("Menu",function($menu){
        $menu->add("Application",
            [
                "class" => "header",
                'raw' => true,
            ]
        );
        $menu->add('Home',
            [
                "url" => '',
                "class" => "treeview"
            ]
        );
    });

Generates

    <ul>
    <li class="header">Application</li>
    <li class="treeview"><a href="http://menu.dev">Home</a></li>
    </ul>

Hope that helps?

**Comment by dustingraham** [comment]
Please re-open if you have any issues.
