### ISSUE TITLE
breadcrumbs

### ISSUE THREAD

**Issue by kgtu** [lavary/laravel-menu#190]
It will be good to add breadcrumbs function for active element

**Comment by dustingraham** [comment]
Hm, so like a Menu::renderBreadcrumbs that would use some breadcrumb template and each of the parent items?

**Comment by kgtu** [comment]
It will be enought to have some method, wich return an array of path to current menu from top

**Comment by dustingraham** [comment]
Thanks to @aronduby this was fixed two years ago. ;)

https://github.com/lavary/laravel-menu#crumb-menu

    {!! Menu::get('primary')->crumbMenu()->asUl() !!}

Merged with #75
