### ISSUE TITLE
Get the active state of an item

### ISSUE THREAD

**Issue by schonhose** [lavary/laravel-menu#196]
I use a custom blade template to add my menu. In this blade template I would like to do something like:

`@foreach($items as $item)`
`   @if ($item->active)`
`      // do something`
`   @endif`
`@endforeach` 

It seems that when I loop over children you can check if they are active in this way, but for the main container this doesn't seem to work. How can I check if the menu item is an active link?

Ah never mind.... #108

**Comment by dustingraham** [comment]
All good then? :)

**Comment by schonhose** [comment]
Yeah, got it sorted out.  I did a search but it came up empty. Posted the question,rephrased the search and found it.
