### ISSUE TITLE
There is a period in id. It interferes with the Bootstrap.js.

### ISSUE THREAD

**Issue by taxusorg** [lavary/laravel-menu#197]
`uniqid('id-', true)` will get an ID example 'id-59ec2db4b69ed3.25044118'.
There is a problem like "$('#item-id-59ec2db4b69ed3.25044118');" jQuery will finding element id='item-id-59ec2db4b69ed3' and class='25044118'
If id is too slow, use md5 and uniqid `'id-'.md5(uniqid(null, true))`

**Comment by dustingraham** [comment]
Darn, good point. This was changed with #170 but we'll figure out a better solution.

**Comment by dustingraham** [comment]
Fixed with latest commit. Thanks @taxusorg
