### ISSUE TITLE
Question: is there an other way to pass an icon for a menu item?

### ISSUE THREAD

**Issue by schonhose** [lavary/laravel-menu#198]
Currently I use the `prepend` option to add an icon to a menu item. Problem is that the icon is now contained in the div that is actually hidden when viewing the site on a mobile.

Is there any other way I can add an icon to a menu item so I can access it into blade as `$item->icon` for example? This allows me to move the icon a few levels higher in the dom so it is always visible.

Does this make sense?

**Comment by dustingraham** [comment]
Could you let me know if using `before` rather than `prepend` places the markup where you need it?

**Comment by schonhose** [comment]
No, that doesn't help. I cannot see the markup anywhere when I use that. My simplified markup consists of:
```
<a>
   <!-- Here the markup for the icon should be --> 
   <span class="left-menu-link-info">
      <span class="link-name">{!! $item->title !!}</span>
      <span class="link-state"></span>
   </span>
</a>
```
With the `prepend` the icon is placed in the span `link-name` that is part of the span `left-menu-link-info`. The latter span and it contents (including the prepended icon) is hidden on large devices. Hence, when I place the image outside this span, it will always show (as denoted by the comment).

**Comment by dustingraham** [comment]
Ah, on the latest version `before` will prepend it outside of the `<a>` tag.

It appears you are rendering this using a custom view?

One thing you could do is... instead of `$item->prepend('<i class="icon"></i>')`

You could try: `$item->data('icon', '<i class="icon"></i>');`

Then

    <a>
        {{ is_null($item->data('icon')) ? '' : $item->data('icon') }}
        <span class="left-menu-link-info">

**Comment by schonhose** [comment]
Thanks, this works!

**Comment by dustingraham** [comment]
Excellent.
