### ISSUE TITLE
Before and after error

### ISSUE THREAD

**Issue by bfuzze** [lavary/laravel-menu#201]
I think this is just a documentation issue, but the example you give for the [Before and After](https://github.com/lavary/laravel-menu#before-and-after) section, produces an exception: **Call to undefined method Lavary\Menu\Item::link()**

After a while I figured out this works:
`
$submenu = $menu->add('menu-name',    ['url'  => '#', 'class' => 'navbar dropdown']);
$submenu->link->attr(['class' => 'dropdown-toggle', 'data-toggle' => 'dropdown']);
$submenu->after('rendered-submenu-html...');
`
Thanks.

**Comment by dustingraham** [comment]
Good point. You figured it out. Fixed documentation. Thanks.
