### ISSUE TITLE
Dynamic sub-menu

### ISSUE THREAD

**Issue by alalfakawma** [lavary/laravel-menu#203]
How do I create dynamic sub-menus? My menus are being generated from the database according to my ?pages. Is there a way to dynamically add sub-menus? Adding parent menus is not a problem but adding sub-menus becomes a problem as we have to use object properties which does not work with a variable, I have tried using eval() function to parse a string as php code but it's not the most efficient way and I just want to know if it possible to do this. Thank you.

**Comment by dustingraham** [comment]
To create a sub-menu you can use `$menu->get('parent')->add('child')`

https://github.com/lavary/laravel-menu#sub-items

Could you give a more concrete example of what you're trying to do? I don't quite understand where this becomes a problem in your explanation.

**Comment by alalfakawma** [comment]
I actually figured this out on my own, this can be closed. I didn't realize that the menu creation returns an object to a variable. Thanks for the reply anyhow.
