### ISSUE TITLE
Active class not added when url has parameter

### ISSUE THREAD

**Issue by yuliantosb** [lavary/laravel-menu#205]
Hello sir, I want to asking a question,
when url is same like in menu class active is set, but when url has parameter class active is unset, my code like this

```
\Menu::make('MyNavBar', function ($menu) {
            $menu->add('Dashboard', ['route' => 'dashboard']);
 });

```
when url is `http://project.dev/dashboard `then menu class is active but if the url is  `http://project.dev/dashboard/user` the class is not active, should I add `$menu->dashboard->add('User', ['route' => 'dashboard.user'])` on my code? but I don't want to add child menu, how to handle this?

I'm sorry, my English very bad.

**Comment by dustingraham** [comment]
Try:

```
$menu->add('Dashboard', ['route' => 'dashboard'])->active('dashboard/*');
```

**Comment by yuliantosb** [comment]
@dustingraham Thank you sir, it's really working, :+1:
