### ISSUE TITLE
URLs with query parameters are not set active

### ISSUE THREAD

**Issue by ThomasRitter75** [lavary/laravel-menu#206]
checkActivationStatus in item tests on `$this->url() == \Request::url()`, which removes *query* parameters, as it uses Request::url, which is 
`    return rtrim(preg_replace('/\?.*/', '', $this->getUri()), '/');`

So checkActivationStatus should test 
`    $this->url() == \Request::url() || $this->url() == \Request::fullUrl()`
Otherwise menu items with query parameters are not activated properly.

**Comment by dustingraham** [comment]
I have not tested, but that makes sense.

**Comment by ThomasRitter75** [comment]
I have it running in a test environment and it works perfectly.
