### ISSUE TITLE
[Question] How to make active in link

### ISSUE THREAD

**Issue by yuliantosb** [lavary/laravel-menu#209]
Hello, sir I have a question, how to make active instead of anchor attribute, the default give a active css class on ul tag, but I want to a tag

```
<li>
       <a class="active" href="http://localhost/laravel/public/home">Home</a>
</li>
<li>
       <a href="http://localhost/laravel/public/user">User Account</a>
</li>
```

How to make like that?
My code like this

```
$menu->add('Home', ['url' => 'home'])
                ->link
                ->active('home/*');

$menu->add('User Account', ['url' => 'user'])
                ->link
                ->active('user/*');
```

but, not working, the html rendered all link set active, I'm sorry my English bad. Thanks

**Comment by dustingraham** [comment]
Remove the `->link` part.
```
$menu->add('Home', ['url' => 'home'])->active('home/*');
$menu->add('User Account', ['url' => 'user'])->active('user/*');
```

And, in `settings.php` set `'active_element' => 'link',`

To use your own settings, publish config.

`php artisan vendor:publish --provider="Lavary\Menu\ServiceProvider"`

**Comment by yuliantosb** [comment]
@dustingraham This is great sir, thanks again, is it can also use both li class="active" and a class="acitive" ? I'm sorry for my bad question, but html theme that I use is very bad it need li tag class active and also a class active for the active bar, But if there's no way to handle it's okay, you are very helpful anyway

**Comment by dustingraham** [comment]
No. Only one or the other.

The way that CSS works, is that you may be able to only use it on the parent class, and change the CSS.

Example if CSS is:

```
li.active { background-color: #f00; }
a.active { color:#0f0; }
```
You could change it to...

```
li.active { background-color: #f00; }
li.active > a { color:#0f0; }
```

The `>` symbol means the immediate child. This way it won't also target children multiple levels deep. But it will also remove the requirement of the class to be on both.

But, this library is not designed to apply it to both. You could extend the `Item` class, and overwrite `activate` or call `activate` yourself targeting the item and the link to call active if you're crafty.

**Comment by yuliantosb** [comment]
@dustingraham Thanks for the tips
