### ISSUE TITLE
[Question] How to make wilcard with get parameter

### ISSUE THREAD

**Issue by yuliantosb** [lavary/laravel-menu#210]
Hello again sir, :D I want to ask, how to make active url with wildcard parameter get,
the url like this

```
/category?type=post
/category/create?type=post
```
here's my code

```
$menu->add('Post', 'javascript:void(0)')
                    ->prepend('<i class="mdi mdi-file-document-box"></i>')
                    ->append('<span class="menu-arrow"></span>')
                    ->active('admin/post/*');
$menu->post->add('All Post', 'admin/post')->active('admin/post/*');
$menu->post->add('Category', 'admin/category?type=post')->active('admin/category/*?type=post');
```
but the code not working? Is there any solution to handle this? I'm sorry I'm too muck ask, your answer very help me,

**Comment by dustingraham** [comment]
Could you try

`$menu->page->add('Category', 'admin/category?type=page')->active('admin/category/*\?type=post');`

**Comment by yuliantosb** [comment]
@dustingraham It's not working sir

**Comment by dustingraham** [comment]
Hi @yuliantosb I just looked into this more. It looks like Laravel `\Request::path()` does not include the `?key=value` parameters. So, this will not work.

It could work if you did something like...

`$menu->page->add('Category', 'admin/category?type=page')->active('admin/category/*/post');`

Then it would match all of the following.

```
/admin/category/post
/admin/category/create/post
/admin/category/edit/post
```

But, the `?key=value` won't affect laravel-menu.

**Comment by dustingraham** [comment]
Let me know if you have any other questions.
