### ISSUE TITLE
Target="_blank"

### ISSUE THREAD

**Issue by bulfaitelo** [lavary/laravel-menu#213]
How can I add the `target="_ blank"` parameter in the `link->href('url')`?

**Comment by dustingraham** [comment]
Could you try `link->attr(['target' => '_blank'])`

https://github.com/lavary/laravel-menu#manipulating-links

**Comment by ultrono** [comment]
```link->attr('target', '_blank')``` also works if you're only passing single attribute.

**Comment by dustingraham** [comment]
Due to the thumbs up, going to mark this as resolved.
