### ISSUE TITLE
help on null asUI()

### ISSUE THREAD

**Issue by yappy1985** [lavary/laravel-menu#214]
(1/1) FatalErrorExceptionCall to a member function asUl() on null

Hi Support,
Have been getting the above error after following your middleware example. using version 1.7. Registered in Kernal, providers, alias. Would like some help. Thanks in advance

in middleware
public function handle($request, Closure $next)
    {
        Menu::make('navMenu', function($menu) {
            $menu->add('Home', '/');
            $menu->add('About', '/about');
            $menu->add('Blog', '/blog');
            $menu->add('Contact Me', '/contact-me');
        });

        return $next($request);
    }

in blade
<div>
        {!! Menu::get('navMenu')->asUl() !!}
</div>

**Comment by yappy1985** [comment]
register kernal as middleware instead of routemiddeware resolved the problem

**Comment by kamrava** [comment]
> register kernal as middleware instead of routemiddeware resolved the problem

middlewareGroups or middleware?

**Comment by dustingraham** [comment]
I think his point was that he added it to `$routeMiddleware` as opposed to `$middlewareGroups`

https://github.com/lavary/laravel-menu#getting-started

Yes, add it to `$middlewareGroups` and it should be ok.

**Comment by kamrava** [comment]
I have a weird problem!

Sometimes return this error for me:

`ERROR: Call to a member function asUl() on null
`

And after this error if I refresh the page everything works fine!
Just first time(sometimes) return that error!

**Comment by dustingraham** [comment]
Sounds like a race condition. If you have it in middlewareGroups, you should create a new ticket, with more error information.

**Comment by kamrava** [comment]
Yes I have it in middlewareGroups.
I'll create a new ticket.
Thank You
