### ISSUE TITLE
Property to nested <ul>

### ISSUE THREAD

**Issue by PraneyRaghu** [lavary/laravel-menu#215]
How can I assign class property to nested 'ul' instead of 'li' ?

**Comment by dustingraham** [comment]
Could you try `{!! $MenuName->asUl(null, ['class' => 'nested-ul-class'] ) !!}`

Some references:
 - https://github.com/lavary/laravel-menu#rendering-methods
 - https://github.com/lavary/laravel-menu/blob/master/src/Lavary/Menu/Builder.php#L663

Alternatively, you can create a custom view.

https://github.com/lavary/laravel-menu#advanced-usage

See custom menu item, where the nested sub-menus would be from custom menu item view.

**Comment by Hackman1993** [comment]
Actually,I still need help with this problem, using asUl function can resolve problem as single problem,but problem still exist in 3 lvl problem,
