### ISSUE TITLE
Output subitem of the active parent

### ISSUE THREAD

**Issue by YuPilipchinets** [lavary/laravel-menu#219]
Sorry for my language.
I want to deduce all the subparagraphs of the active parent in the blade template, but I do not know how to do it.
My code:
Middleware:

> \Menu::make('SiteNavBar', function ($menu) {
> 			$menuItems = Category::where('public', 1)->get();
> 			foreach ($menuItems as $items) {
> 				if ($items->parent_id == 0) {
> 					$menu->add($items->title, ['url' => $items->uri])->id($items->id);
> 				} else {
> 					if ($menu->find($items->parent_id)) {
> 						$menu->find($items->parent_id)->add($items->title, ['url' => $items->uri])->id($items->id);
> 					}
> 				}
> 			}
> 		});

Blade template:

> @foreach ($items as $item)
> 	@foreach($item->children() as $child)
> 		<ul class="nav flex-column navbar-custom">
> 			<li class="nav-item {{ (URL::current() == $child->url()) ? " active " : '' }}">
> 				<a href="{{ $child->url() }}" class="nav-link">{{ $child->title }}</a>
> 			</li>
> 		</ul>
> 	@endforeach
> @endforeach

Help me please!

**Comment by dustingraham** [comment]
I don't understand.

What is wrong? Can you provide an example of what this does output, and what it should output?

Thanks.

**Comment by YuPilipchinets** [comment]
when I select a subitem in the top menu of item 1, I want to display all the subitems of item 1

**Comment by YuPilipchinets** [comment]
This is the code in the blade template:
```
@foreach ($items as $item) //parent items
	@foreach($item->children() as $child) //subitems
		@if ($item->id == $child->parent)
			<ul class="nav flex-column navbar-custom">
				<li class="nav-item {{ (URL::current() == $child->url()) ? " active " : '' }}">
					<a href="{{ $child->url() }}" class="nav-link">{{ $child->title }}</a>
				</li>
			</ul>	
		@endif
	@endforeach
@endforeach
```

**Comment by dustingraham** [comment]
Does this code show all sub-items for all menu items?

You might try something like `if ($menu->active()->id == $item->id)` or try `$menu->active()->hasParent()` and `->parent()` to check the parent ID and compare.

Let me know if that helps.

**Comment by YuPilipchinets** [comment]
I did so:
```
@foreach ($items as $item)
	@foreach($item->children() as $child)
		@if ($child->active) // if item or subitem active
			@php
				$child1 = $child->active()->parent //$child = parent_id
			@endphp	 
		@endif
		@if ($child1 == $item->id) //if subitem->parent_id == item->id
			<ul class="nav flex-column navbar-custom">
				<li class="nav-item {{ $child->active ? " active " : '' }}">
					<a href="{{ $child->url() }}" class="nav-link">{{ $child->title }}</a>
				</li>
			</ul>
		@endif
	@endforeach
@endforeach
```
It's works! But not good...

**Comment by YuPilipchinets** [comment]
It does not work correctly, I think further

**Comment by dustingraham** [comment]
Can you give me an example of the data? What's wrong?

**Comment by YuPilipchinets** [comment]
Database structure:

```
1. id
2. parent_id
3. title
4. uri

```
Data in the table:

```
id	parent_id	title		uri
1	0		item-1		app/item1
2	1		subitem-1.1	app/item1/subitem11
3	1		subitem-1.2	app/item1/subitem12
4	1		subitem-1.3	app/item1/subitem13
5	0		item-2		app/item2
6	5		subitem-2.1	app/item2/subitem21
7	5		subitem-2.2	app/item2/subitem22
8	0		item-3		app/item3
9	8		subitem-3.1	app/item3/subitem31
```

if I select subitem-1.2, then on the page I should deduce all subitems of item-1, if I select subitem-2.1, then on page should output all subitems of item-2.

**Comment by YuPilipchinets** [comment]
This code it's works:
```

@foreach ($items as $item)
	@foreach ($item->children() as $child)
		@if ($child->active)
			@foreach ($item->children() as $subitem)
				<ul class="nav flex-column navbar-custom">
					<li class="nav-item {{ $subitem->active ? " active " : '' }}">
						<a href="{{ $subitem->url() }}" class="nav-link">{{ $subitem->title }}</a>
					</li>
				</ul>
			@endforeach
		@endif
	@endforeach
@endforeach
```

**Comment by YuPilipchinets** [comment]
While working, but you need to thoroughly test.
The topic can be closed ...

**Comment by dustingraham** [comment]
Thank you for reporting this. I'm glad you found a solution.
