### ISSUE TITLE
Active Submenu and Parent for Patterns

### ISSUE THREAD

**Issue by nasirkhan** [lavary/laravel-menu#221]
I want to active my submenu using pattern. 

I tried to use the suggested approach to `active` the menu as follows, but it did not works. Here i want to make the User menu active for all the url like `/users*`

```php

$accessControl->add('<i class="icon-people"></i> Users', [
        'route' => 'backend.users.index',
        'class' => 'nav-item',
    ])
    ->active("/users*")
    ->data('order', 79)
    ->link->attr([
        'class' => 'nav-link',
    ]);

```

Here is how my `GenerateMenus` looks like, 

```php
\Menu::make('admin_sidebar', function ($menu) {
    // Dashboard
    $menu->add('<i class="icon-speedometer"></i> Dashboard', [
        'route' => 'backend.dashboard',
        'class' => 'nav-item',
    ])
    ->data('order', 1)
    ->link->attr([
        'class' => 'nav-link',
    ]);

    // Separator: Access Management
    $menu->add('Access Management', [
        'class' => 'nav-title',
    ])
    ->data('order', 77);

    // Access Control Dropdown
    $accessControl = $menu->add('<i class="icon-key"></i> Access Control', [
        'class' => 'nav-item nav-dropdown',
    ])
    ->data('order', 78);
    $accessControl->link->attr([
        'class' => 'nav-link nav-dropdown-toggle',
        'href'  => '#',
    ]);

    // Submenu: Users
    $accessControl->add('<i class="icon-people"></i> Users', [
        'route' => 'backend.users.index',
        'class' => 'nav-item',
    ])
    ->active("/users*")
    ->data('order', 79)
    ->link->attr([
        'class' => 'nav-link',
    ]);
    // Submenu: Roles
    $accessControl->add('<i class="icon-people"></i> Roles', [
        'route' => 'backend.roles.index',
        'class' => 'nav-item',
    ])
    ->data('order', 80)
    ->link->attr([
        'class' => 'nav-link',
    ]);
})->sortBy('order');
```

**Comment by dustingraham** [comment]
Yea, I had a similar issue. Here's what I'm doing in my project...

```            $menu->add('User Accounts', [
                'action' => 'UserController@userAccounts',
            ])->data([
                'permissions' => 'users.view',
                'activematches' => 'portal/users/*',
            ]);```

Then I used a filter...

```$menu->filter(function ($item) {
                // Check if route is active.
                if (Request::url() === rtrim($item->url(), '#/')) {
                    $item->active();
                }

                // See if there are any pattern matches.
                if ($item->activematches) {
                    $matches = is_array($item->activematches) ? $item->activematches : [$item->activematches];
                    foreach ($matches as $pattern) {
                        $pattern = ltrim(preg_replace('/\/\*/', '(/.*)?', $pattern), '/');
                        if (preg_match("@^{$pattern}\z@", \Request::path())) {
                            $item->activate();
                        }
                    }
                }
                return true;
            });```

**Comment by nasirkhan** [comment]
@dustingraham thanks for guiding. But I unfortunately your code did not work for me. the `$item->url()` returning null always. I tried to find options to get the URL from the menu item, but did not find anything. 

Can you please look into the issue again and help me to resolve.

**Comment by dustingraham** [comment]
In the code, you can see the `function add()`
https://github.com/lavary/laravel-menu/blob/master/src/Lavary/Menu/Item.php#L140

It expects either the options array parameter to have a 'url' parameter, or you can pass the url as the second parameter and options as the third parameter.

Then, the `function url()`
https://github.com/lavary/laravel-menu/blob/master/src/Lavary/Menu/Item.php#L223

Will return either `$this->link->href` or calls dispatch to generate the link.

Since you are passing routes, I would expect it to call builder->dispatch to build the link that is returned.

You will need to figure out how to get the URL from the $item if you want to use the filter I suggested. This is simply what I have done to make it work for me, I'm not sure if it will work for you. I think you understand the idea though. Attempting to match the current route against the url or active matches.

You could try commenting out those three lines with the $item->url() and just use the second part with the active matches.

**Comment by nasirkhan** [comment]
thank you now i understand your point. I was assuming that there might be a method named `url()` and that is why asked you again. 

Your code works. I made some changes on pattern matching area. Laravel have a helper method `str_is()` to match string patterns. I used that instead of `preg_match()` and wring matches by myself. You may try this too. 

This helped me to get partial success. The `active` is working, but i also need to add a class to parent `li` item. Do you have any idea about this? my project is located at https://github.com/nasirkhan/laravel-starter

```
if ($item->activematches) {

    $matches = is_array($item->activematches) ? $item->activematches : [$item->activematches];

    foreach ($matches as $pattern) {
        if (str_is($pattern, \Request::path())) {
            $item->activate();
            // dd($item);
        }
    }
}
```

**Comment by dustingraham** [comment]
Perhaps try `$item->parent()` to access the parent item, and apply the necessary tags that way? There is also a `$item->hasParent()` method.

https://github.com/lavary/laravel-menu/blob/master/src/Lavary/Menu/Item.php#L311

**Comment by aloksoni11** [comment]
I want to add class active in list-item if its child unorder-list's list-item has active.
How can I do this in laravel ? Please suggest to me.
