### ISSUE TITLE
Bootstrap 4 Compatibility Question

### ISSUE THREAD

**Issue by audetcameron** [lavary/laravel-menu#223]
![screen shot 2018-07-17 at 9 56 45 am](https://user-images.githubusercontent.com/6738453/42821963-cb76e1ac-89a7-11e8-8c8a-5ff3807af840.png)

Bootstrap 4 uses div elements to wrap the drop-down menu.  The dropdowns are a elements.
Is there a way to tell your menu builder to use a div for a submenu and anchor elements instead of li's inside the submenu?

**Comment by dustingraham** [comment]
Check out https://github.com/lavary/laravel-menu#menu-as-div

**Comment by ttimot24** [comment]
Doesn't work with asDiv().
