### ISSUE TITLE
Error on sorting the items by passing a closure

### ISSUE THREAD

**Issue by X-Coder** [lavary/laravel-menu#224]
When I try to do custom sorting on v1.7.2/Laravel 5.6 like
`$menu->sortBy(
            function ($items) {
            }
        );`

I get this error exception:
"Property [to] does not exist on this collection instance"

line 467 of Lavary\Menu\Builder raised this exception:
`$rslt = call_user_func($sort_by, $this->items->to[]);`

The $this->items type is of Lavary\Menu\Collection.
But I couldn't figure why there is a missing "to" property on the item collection.

I need custom sort because I want to sort by nickname or title and do some custom rendering. The built in sortBy function does only seem to handle numeric sorts.

**Comment by X-Coder** [comment]
Found the cause:
commit https://github.com/lavary/laravel-menu/commit/c9be1d2e724077576cde4c394c1483d121723457#diff-b9eb6164d978c4b582e966bf32cb5fe7R466 messed it up and converted toArray into to[].

**Comment by dustingraham** [comment]
Thanks.

Fixed with 1ee9472bca672a14512e6866e53edbaee5250dbd

**Comment by X-Coder** [comment]
Thank you much for the very fast bug fix.
