### ISSUE TITLE
Error on sorting the items by passing a closure #2

### ISSUE THREAD

**Issue by X-Coder** [lavary/laravel-menu#225]
There is another bug when you try to do custom sort
`$menu->sortBy(function($items){
    return $items;
});`

https://github.com/lavary/laravel-menu/blob/1ee9472bca672a14512e6866e53edbaee5250dbd/src/Lavary/Menu/Builder.php#L475

I think there is a missing `return $this;` after this line otherwise you would start the built in sorting after the custom sorting call and passing the closure to $sort_by in line 480 https://github.com/lavary/laravel-menu/blob/1ee9472bca672a14512e6866e53edbaee5250dbd/src/Lavary/Menu/Builder.php#L480 leading to a "Object of class Closure could not be converted to string" exception.

**Comment by dustingraham** [comment]
Thanks for figuring that out.
