### ISSUE TITLE
roots not return divide

### ISSUE THREAD

**Issue by carlituxman** [lavary/laravel-menu#227]
If we use 
@include(config('laravel-menu.views.bootstrap-items'), ['items' => $mainNav->roots()])

not can use the divide li

how can we do?

**Comment by dustingraham** [comment]
Can you review the readme, and give me some more information or examples of what you're trying?

https://github.com/lavary/laravel-menu#getting-started

**Comment by carlituxman** [comment]
I'm using the rendering with template with ->roots
like in the readme: Menu as Bootstrap 3 Navbar

<ul class="nav navbar-nav navbar-right">

        @include(config('laravel-menu.views.bootstrap-items'), ['items' => $loginNav->roots()])

      </ul>

**Comment by carlituxman** [comment]
The problem is when using ->roots() not return the divides

**Comment by dustingraham** [comment]
Dividers are not items. They are attributes on the item. Try this.

    echo '<pre>';
    foreach($menu->roots() as $item)
    {
        echo $item->title .'<br>';
        echo 'Has Divider: '.($item->divider ? 'Yes' : 'No').'<br>';
        echo '<hr>';
    }
    exit;

**Comment by carlituxman** [comment]
roots not return dividers.
this bucle all has divider = NO

**Comment by dustingraham** [comment]
Here's some example code:

    \Menu::make('sMenu', function($menu) {
        $menu->group(['prefix' => 'pages', 'data-info' => 'test'], function($m){
            $about = $m->add('About', 'about');
            $about->group(['prefix' => 'about', 'data-role' => 'navigation'], function($a){
                $a->add('Who we are', 'who-we-are?')->divide();
                $a->add('What we do?', 'what-we-do');
                $a->add('Our Goals', 'our-goals');
            });
        });
        
        //////////////////// testing for issue //
        echo '<pre>';
        foreach($menu->roots() as $item)
        {
            echo $item->title .'<br>';
            echo 'Has Divider: '.($item->divider ? 'Yes' : 'No').'<br>';
            echo '<hr>';
        }
        exit;
        ////////////////////
    });


Which results in

```
About
Has Divider: No
Who we are
Has Divider: Yes
What we do?
Has Divider: No
Our Goals
Has Divider: No
```

This shows that roots() returns the items, and the divider is on the item. Please provide full sample code if this is not working for you.
