### ISSUE TITLE
Route Parameters

### ISSUE THREAD

**Issue by fatoskurtishi** [lavary/laravel-menu#228]
Hi i have a saved my menu items in database and i want to generate a menu like this:

> Menu::make('MyNavBar', function ($menu) use ($items) {
>     foreach($items as $item)
>     {
>         $menu->add($item->name, ['route' => [$item->route, $item->route_parms]]);
>     }
> });

I get: Array to string conversion

**$item->route_parms is casted as array.**
Any help how can i pass that array to route parameters ?

**Comment by dustingraham** [comment]
Menu::make('MyNavBar', function ($menu) use ($items) {
        foreach($items as $item)
        {
            $params = $item->route_params;
            array_unshift($params, $item->route);
            $menu->add($item->name, ['route' => $params]);
        }
    });

https://github.com/lavary/laravel-menu/blob/master/src/Lavary/Menu/Builder.php#L408

It slices the first element off the options. So you need to combine the items.
