### ISSUE TITLE
Class App\Http\Middleware\GenerateMenus does not exist

### ISSUE THREAD

**Issue by saulohdz** [lavary/laravel-menu#234]
I have Laravel 5.6
Follow the installation instructions and send this error when 
add in middlewares :

ReflectionException (-1)
Class App\Http\Middleware\GenerateMenus does not exist

**Comment by dustingraham** [comment]
I have not tested this lately. But, to confirm you added the middleware to the kernel?

https://github.com/lavary/laravel-menu/#getting-started

**Comment by saulohdz** [comment]
Ff course, just when I add it to the middleware is when I send that error

**Comment by dustingraham** [comment]
Well, shoot. I just left work and I don't have a good way to work on this while at home.

I can test this on Monday, but in the mean time, do you know what is wrong?

Generating middleware is a laravel thing. Not specific to this package. I took a look at the laravel 5.6 docs and it looks like it is unchanged. I believe I have tested this in 5.6 before.

Are the namespaces correct? Paths to the files correct?

Any additional information in the stack trace? Did you move the file after it was generated? Did you add a Menu:: declaration to the handle function? Care to share your GenerateMenus middleware class in full? Maybe I'll notice something.

**Comment by saulohdz** [comment]
Review the paths and  make changes and Now appear this:

class GenerateMenus
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        \Lavary\Menu\Menu::make('MenuPaseLista', function ($menu) {
            $menu->add('Inicio',"/");
            $menu->add('Catalogos')->get()->addmenu('Eventos', 'eventos');
            $menu->add('Catalogos')->get()->addmenu('Lugares Eventos', 'lugarEvento');
            $menu->add('Catalogos')->get()->addmenu('Usuarios', 'usuarios');
            $menu->add('Mi Perfil')->get()->addmenu('Cambiar Contraseña','');
            $menu->add('Mi Perfil')->get()->addmenu('Ver Perfil','');
            $menu->add('Salir', 'logout');
        });
        return $next($request);
    }
}
 
**"Non-static method Lavary\Menu\Menu::make() should not be called statically"**

**Comment by dustingraham** [comment]
Please try `\Menu::make` instead of `\Lavary\Menu\Menu::make`

**Comment by saulohdz** [comment]
solved, thank you very much
