### ISSUE TITLE
@lm-attrs is not loaded for PHPUnit tests

### ISSUE THREAD

**Issue by Xiphoseer** [lavary/laravel-menu#236]
When using this library, I ran into an issue, where on a clean cache, running the PHPUnit tests would generate a wrong view cache that had not processed the `@lm-attrs` directives. When filling the cache any other way, the problem went away. Is there something I need to do to call the boot() method of the ServiceProvider while testing? It seems to me as if Blade just didn't know that directive at that point.

**Comment by dustingraham** [comment]
Hm, I don't have much experience with the unit tests.

The directive is defined here: https://github.com/lavary/laravel-menu/blob/master/src/Lavary/Menu/blade/lm-attrs.php

Maybe it needs to be included explicitly somewhere.

**Comment by Xiphoseer** [comment]
Yeah, I dug around the code to find something useful. I could try to load that file directly from the `vendor` folder, although that would be quite ugly. Setting `$defer=false` on the ServiceProvider doesn't seem to help either. The only difference I've found is that the Browser uses the HTTP Kernel, while the tests use the console Kernel. How that would change anything about loading laravel-menu is unclear to me though.

**Comment by dustingraham** [comment]
https://github.com/lavary/laravel-menu/blob/master/src/Lavary/Menu/ServiceProvider.php#L35

This seems a little weird to have the require like this.

I imagine there's a better way to define blade extensions endorsed by Laravel.

**Comment by Xiphoseer** [comment]
So a bit more testing revealed that is really seems to be the require_once. My current understanding of the issue is as follows:

- We start with a clean view cache
- The tests create an application instance, booting the Laravy\Menu\ServiceProvider
- The require_once is triggered and called
- The first test does not use the template and gets cleaned up
- Some later test creates an application instance
- The require_once is skipped, the extends are not loaded
- The test uses the template thus filling the view cache in a bugged way
- All subsequent requests use the cache until that is reset
- Regenerating works, because every request is bootstrapped separately

So the `require_once` is the culprit in my book.

Additionally, looking at the laravel docs, `Blade::extend` isn't even mentioned. To me, that implies that it is an advanced use case (which are sadly not documented well in Laravel), or that it is an internal function that should not be used.

I tried recreating the feature using the much cleaner `Blade::directive`, which worked fine as long as the directive name didn't use a `-`. I may put up a pull request later today, which removes the `require_once` and adds `lm_attrs` and `lm_endattrs` directives and maybe the current extensions as deprecated for compatability.

**Comment by dustingraham** [comment]
Resolved with #237
