### ISSUE TITLE
Missing space in bootstrap-navbar-items.blade.php

### ISSUE THREAD

**Issue by miikkadriveco** [lavary/laravel-menu#240]
In file Lavary/Menu/resources/views/bootstrap-navbar-items.blade.php
`<a@lm_attrs($item->link)`
causes an error (at least with Laravel 5.2)

The error is fixed by adding a space between <a and @lm_attrs like so
`<a @lm_attrs($item->link)`

**Comment by dustingraham** [comment]
Similar issue to #237

**Comment by dustingraham** [comment]
Should be fixed with v1.7.5

Thanks.
