### ISSUE TITLE
Update to 1.7.4 breaks the html code 

### ISSUE THREAD

**Issue by sebastiandeppisch** [lavary/laravel-menu#241]
Laravel version: v5.5.45

After updating from 1.7.3 to 1.7.4 (and deleting the template cache) my html code was messed up.
Before: 
![image](https://user-images.githubusercontent.com/3171655/55884714-d0f71d80-5ba8-11e9-82b2-092b609f4eb5.png)

After: 
![image](https://user-images.githubusercontent.com/3171655/55884732-d9e7ef00-5ba8-11e9-8f9f-5e59b1d15cdd.png)

Directly after updating it is still working. It just occurred after deleting the template cache.
In one of the cache files this was changed: 

`    <?php if($item->link): ?> <a<?php $lm_attrs = $item->link->attr(); ob_start(); ?> <?php if($item->hasChildren()): ?> class="nav-link dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" <?php else: ?> class="nav-link" <?php endif; ?> <?php echo \Lavary\Menu\Builder::mergeStatic(ob_get_clean(), $lm_attrs); ?> href="<?php echo $item->url(); ?>">`
To this: 

`    <?php if($item->link): ?> <a@lm_attrs($item->link) <?php if($item->hasChildren()): ?> class="nav-link dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" <?php else: ?> class="nav-link" <?php endif; ?> <?php echo \Lavary\Menu\Builder::mergeStatic(ob_get_clean(), $lm_attrs); ?> href="<?php echo $item->url(); ?>">`

When i undo this and use the old cache file, the html code isn't messed up anymore with the new version. 

I included laravel-menu this way: 
```
<ul class="nav navbar-nav">
    @include(config('laravel-menu.views.bootstrap-items'), ['items' => Menu::get('main')->roots()])
</ul>
```

**Comment by dustingraham** [comment]
Similar to #240 can you check laravel-menu.views.bootstrap-items and add a space between `<a` and `@lm_attrs`

I've fixed it here: https://github.com/lavary/laravel-menu/blob/master/src/Lavary/Menu/resources/views/bootstrap-navbar-items.blade.php

**Comment by sebastiandeppisch** [comment]
I updated to 1.7.5, now it is working again. Thank you.
