### ISSUE TITLE
raw() without prefix?

### ISSUE THREAD

**Issue by ToeiRei** [lavary/laravel-menu#242]
I'm working on a project where the design requires me to place some weird stuff in the menu in between the `<ul>` tags, but *without* `<li>`.

So far I figured, that `raw()` fits my purpose best - I'd just have to get rid of `<li>` for those entries - is that possible?

**Comment by dustingraham** [comment]
It can't suppress the <li> tag for a single entry.

You can take a look at the advanced usage:
 - https://github.com/lavary/laravel-menu#advanced-usage

You can create your own blade template and add some php if/else to conditionally use the <li> tag.

**Comment by ToeiRei** [comment]
ouch. So that's it.

**Comment by dustingraham** [comment]
Here's the default renderer.
 - https://github.com/lavary/laravel-menu/blob/master/src/Lavary/Menu/Builder.php#L612

If you're trying to add a divider, you can see line 648 can add a divider.

There are years of iterative improvements on these functions to make them quite flexible. The next step beyond this is to create a custom blade template, which is quite simple. An example is already provided in the documentation.

Why do you need a non-li tag as a sibling in a ul list?

**Comment by ToeiRei** [comment]
I'm trying to render the sidebar of SB Admin 2. It's awful as it is just that `<ul></ul>` which is the container

**Comment by dustingraham** [comment]
I see. That is awkward.
 - https://startbootstrap.com/previews/sb-admin-2/

I tried wrapping the `<a>` tag inside of an `<li>` tag and it didn't seem to impact the style.

![Screenshot from 2019-05-06 10-11-11](https://user-images.githubusercontent.com/1414400/57242059-5bd00a00-6fe7-11e9-8218-4ab2992f93e7.png)

![Screenshot from 2019-05-06 10-11-22](https://user-images.githubusercontent.com/1414400/57242062-5ecafa80-6fe7-11e9-8293-6b8d641a67cb.png)

**Comment by ToeiRei** [comment]
The whole design is a bit strange every now and then. I was trying to work with a sub-page for the menu being included as described in advanced use. But it seems like I'm losing the attributes like class and prepend.

**Comment by ToeiRei** [comment]
As far as I ported the first menu items over, the logo didn't care, but the sidebar headings seem to care.
