### ISSUE TITLE
I can not activate the "active"

### ISSUE THREAD

**Issue by VConsulting** [lavary/laravel-menu#245]
I can not activate the "active" class on the links to change the color of the active menus.

I'm trying to dynamically replicate admin menu 3:
https://adminlte.io/themes/dev/AdminLTE/pages/UI/icons.html

```
return array(
    'default' => array(
        'auto_activate' => true,
        'activate_parents' => true,
        'active_class' => 'menu-open',
        'restful' => false,
        'cascade_data' => true,
        'rest_base' => '',      // string|array
        'active_element' => 'item',  // item|link
    ),
);
```

The menu works perfectly, now it just me can add the class "active" on the line:
```<a href="#" class="nav-link active">```

How to do ?

Class Test :

```
    public function handle($request, Closure $next)
    {
        \Menu::make('MyNavBar', function ($menu) {
            $menu->add('Users', ['class'=>'nav-item has-treeview'])
                ->prepend('<i class="fa fa-fw fa-users nav-icon"></i><p>')
                ->append('<i class="right fa fa-angle-left"></i></p>')
                    ->link
                        ->attr(['class' => 'nav-link'])
                        ->href('#');

                $menu->users->add('Liste des users', ['route' => 'users'])
                    ->attr(['class' => 'nav-item'])
                    ->prepend('<i class="fa fa-fw fa-list-ul"></i><p>')
                    ->append('</p>')
                    ->link
                        ->attr(['class' => 'nav-link']);

                $menu->users->add('Liste users 2', ['route' => 'users2'])
                    ->attr(['class' => 'nav-item'])
                    ->prepend('<i class="fas fa-circle-o nav-icon"></i><p>')
                    ->append('</p>')
                    ->link
                        ->attr(['class' => 'nav-link']);
        });

        return $next($request);
    }
```

**Comment by dustingraham** [comment]
The auto activate looks at the current URL and compares it with the URL of the menu link, adding the active class if the menu link url matches the current url.

Are you saying that when you are on the route "users2" that the "Liste users 2" is not receiving the active class?

**Comment by VConsulting** [comment]
Yes no active class is added

Currently the line remains:
```<a href="#" class="nav-link">´´´

**Comment by dustingraham** [comment]
If it shows `href="user2"` your routes may not be set up correctly, it should show `href="http://localhost/user2"` then when you navigate to `http://localhost/user2` it should show `class="nav-link active"`

**Comment by VConsulting** [comment]
Inspector :
```
<nav class="mt-2">
    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <li class="nav-item has-treeview menu-open"><a class="nav-link" href="#"><i class="fa fa-fw fa-users nav-icon"></i>
                <p>Users<i class="right fa fa-angle-left"></i></p></a>
            <ul class="nav nav-treeview">
                <li class="nav-item"><a class="nav-link" href="http://127.0.0.1:8000/users"><i class="fa fa-fw fa-list-ul"></i>
                        <p>Liste des users</p></a></li>
                <li class="nav-item"><a class="nav-link" href="http://127.0.0.1:8000/users2"><i class="fas fa-circle-o nav-icon"></i>
                        <p>Liste users 2</p></a></li>
            </ul>
        </li>
    </ul>
</nav>
```

**Comment by VConsulting** [comment]
For now, I have successfully activated the active link with a filter, but not are parent.

```
                $menu->filter(function ($item) {

                    if (Request::url() === rtrim($item->url(), '#/')) {
                        $item->link
                            ->attr(['class' => 'nav-link active']);

                    }
```

**Comment by dustingraham** [comment]
Ah, I was going to write the below. But, then I noticed in your configuration you have: `menu-open` as the active class.

Then in your Inspector, you can see `menu-open` on the first <li> item. So, it looks like it is working. When you set the `'active_class' => 'menu-open',` that tells it to use menu-open as the active class instead of active.

(I was going to write the below, but then discovered the above.)

======

https://github.com/lavary/laravel-menu/blob/master/src/Lavary/Menu/Item.php#L353

This is where the item figures out if it needs to be active. You could try dumping $this->url(), Request::url(), and Request::fullUrl to see if you can see why those are not matching. On line 370 if either of them match, it will set the item to active. Which should add the menu-open class.

Obviously the last post you made with setting the class directly does not take advantage of URL matching, but if that works for you great.

**Comment by VConsulting** [comment]
Yes the menu works, with the class "menu-open" on the LI parent. When I'm on a page the menu is well done.

On the other hand, the child <A href=...> does not receive an "active" or "menu-open" class in order to be able to give it, for example, a different style / class :(

I do not understand why he does not do it, the roads are just yet ...

**Comment by dustingraham** [comment]
The idea here is that `<li class="menu-open"><a href="..."></a></li>` can be targeted like `.menu-open > a` so the class is not added to both `<li>` and `<a>`.

If you *only* needed it on the `<a>` you could change `active_element` to `link`, but if you keep it on the `<li>` item you can target the `<a>` class via child selectors. It is redundant to have an active class on both elements.

**Comment by mckenziearts** [comment]
Same problem here.

My config file looks like :

```php
return array(
    'default' => array(
        'auto_activate' => true,
        'activate_parents' => false,
        'active_class' => 'active',
        'restful' => false,
        'cascade_data' => true,
        'rest_base' => '',      // string|array
        'active_element' => 'link',  // item|link
    ),
);
```

Ma Menu

```php
$dashboard = $item->add('<i class="flaticon2-protection"></i>', ['route' => 'shopper.dashboard', 'class' => 'aside__nav-item']);
            $dashboard->link->attr([
                'class' => 'aside__nav-link',
                'data-toggle' => 'tooltip',
                'data-title' => __('Dashboard'),
                'data-placement' => 'right',
                'data-container' => 'body',
                'data-boundary' => 'window'
            ]);

            $site = $item->add('<i class="flaticon2-browser-1"></i>', ['url' => url('/'), 'class' => 'aside__nav-item']);
            $site->link->attr([
                'class' => 'aside__nav-link',
                'data-toggle' => 'tooltip',
                'data-title' => __('Open site'),
                'data-placement' => 'right',
                'data-container' => 'body',
                'data-boundary' => 'window',
                'target' => '_blank'
            ]);
```

But i don't have active class on my link

**Comment by dustingraham** [comment]
Created separate issue for latest comment/question. Closing this question.
