### ISSUE TITLE
Addition of attributes for Builder::render() function

### ISSUE THREAD

**Issue by fklee** [lavary/laravel-menu#246]
In vendor/lavary/laravel-menu/src/Lavary/Menu/Builder.php L631

if  "$item->attr() = ['class'=>'mystyle'] " then "$item->attr() + $item_attributes" will became ['class'=>'active'] and remove orignal item class.

Result table should merge each attributes.

**Comment by dustinaja** [comment]
Had to read this a couple times.

You're saying that the active class overwrites the attribute array, blowing away a custom set class?

**Comment by dvital1001** [comment]
Yes, It is. Is this the correct behavior? It is don't comfortably for programming menu unfortunately.

**Comment by dustingraham** [comment]
Had to read this a couple times.

You're saying that the active class overwrites the attribute array, blowing away a custom set class?

**Comment by dvital1001** [comment]
Excuse me my english ...

There is a reverse situation. User classes remove the active class.

**Comment by fklee** [comment]
Exact, all previous setted class are replaced by active class.

**Comment by dustingraham** [comment]
Makes sense. I have not validated, but it sounds like it is similar to the linked issue. I'll try to look at it when I can.

**Comment by fklee** [comment]
Just to know if the issue is closed ?

**Comment by dustingraham** [comment]
This is still an open issue. Needs someone to review the two issues and implement an enhancement.

**Comment by fklee** [comment]
OK thanks for the information, do you want me to do a pull request ?

**Comment by dustingraham** [comment]
You're certainly welcome to. Yes, thank you.

**Comment by fklee** [comment]
Done #272

**Comment by dustingraham** [comment]
Thank you. Resolved with #272
