### ISSUE TITLE
How to add php file to load in the body of the page?

### ISSUE THREAD

**Issue by YAMER1** [lavary/laravel-menu#253]
It is necessary that a certain file is selected in the body of the page, selected when the link is clicked.
This is in the dynamic menu, it allows you to create a header and footer page. How this one is done here, I do not know.

I prescribed
Route :: get ('index', ['as' => '/site/main.php', function () {}]);
   $ menu-> add ('Home', ['route' => '/site/main.php']);
This does not work. And it does not work with a slash / instead of an index.

How can I add new pages to the site, while maintaining the menu on each page?

**Comment by dustingraham** [comment]
Closing this for now, please re-open if you still have an issue.

I presume you'll need to handle this in your own code.
