### ISSUE TITLE
Question about usage filters and create menu's

### ISSUE THREAD

**Issue by marcelogarbin** [lavary/laravel-menu#258]
Hello, I'm starting to use this package and learning about the features available. So far I'm enjoying it as it speeds up development as well as makes the code more organized.

But as a beginner, there were some questions about using the filters, which I want to use as in the example [check permissions](https://github.com/lavary/laravel-menu#filtering-the-items).

In my project I work with [Laravel Modules](https://nwidart.com/laravel-modules/v6/introduction), where each module has its provider, in which case I will use them to start the menu. My question is, is it correct to use `Menu::make` on each provider, or should I use it only once?

Another question, is the filter method bound to a `Menu::make` facade, in which case to check the permissions I must create in each new menu or is there somewhere that I must declare the filter for all created instances of the menu?

Thank's your attention. Congratulations on the package! Tips for using the package are also welcome.

**Comment by marcelogarbin** [comment]
another question that came up about groups.

How could I set permissions for an entire group of items?

For individual item I can do the following: `$menu->add('About 1')->data('permission', 'manage_users');` - Ok, that works.

I tried the following for group, but to no avail:
```php
$menu->group(['style' => 'padding: 0'], function($m){
     $m->add('About');
     $m->add('Services');
 })->data('permission', 'manage_users');
```

How could I do in this case? or is the data method only individual?

**Comment by dustingraham** [comment]
As you suspect, ->data() only works on menu items, not groups.

Try using Menu::make in two modules and see what happens. I suspect it will wipe one of them.

You might try calling a Menu::make earlier in your bootstrap, then each module could do a Menu::get in each module to add on to the existing menu.

**Comment by marcelogarbin** [comment]
> As you suspect, ->data() only works on menu items, not groups.
> 
> Try using Menu::make in two modules and see what happens. I suspect it will wipe one of them.
> 
> You might try calling a `\Menu::make` earlier in your bootstrap, then each module could do a Menu::get in each module to add on to the existing menu. 

So I did some testing here with `\Menu::make`, it doesn't reset the other menus declared in other providers. This is good for me because I want to keep the ones that have already been declared.

Would it be incorrect to use multiple `\Menu::make`?

If no problem, I will keep it.

On the question of filtering to verify user permissions.

It would be boring and perhaps unclear to declare this check every time every time, so it would be right to declare it only once.

What I did, I created a new middleware as shown here [in the documentation](https://github.com/lavary/laravel-menu#getting-started) and made my logic inside it. First of all I check if the menu has been declared and then apply what I want to filter.

Example:
`Http/Middleware/CheckMenu.php`
```php
<?php

namespace App\Core\Http\Middleware;

use Closure;
use Illuminate\Support\Facades\Auth;

class CheckMenu
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @param  string|null  $guard
     * @return mixed
     */
    public function handle($request, Closure $next, $guard = null)
    {
        $menu = \Menu::get('painelAside');
        if(isset($menu)){
            // Check permission
            $menu->filter(function($item){
                $permission = $item->data('permission');
                if(isset($permission)){
                    if(is_array($permission) && Auth::user()->hasAnyPermission($permission)){
                        return TRUE;
                    }

                    if(Auth::user()->hasPermissionTo($permission)){
                        return TRUE;
                    }

                    return FALSE;
                }

                return TRUE;
            });
        }

        return $next($request);
    }
}
```

I declare this middleware in the web group.
`Http/Kernel.php`
```php
 protected $middlewareGroups = [
        'web' => [
            ...
            \App\Core\Http\Middleware\CheckMenu::class,
            ...
        ],
];
```

So far it seems to work as expected. I'm using the package [spatie/laravel-permission](https://github.com/spatie/laravel-permission) to check permissions.

What do you think of this logic, can it be used that way or would it have anything better to do?

Thanks for your response.

**Comment by dustingraham** [comment]
This middleware example you've described is exactly what I've been using for an in-house production server for 3+ years with no problem. :)

```
            ->filter(function ($item) {
                // Check permissions!
                if ($item->permissions) {
                    if (is_array($item->permissions)) {
                        return Sentry::getUser()->hasAnyAccess($item->permissions);
                    } else {
                        return Sentry::getUser()->hasAccess($item->permissions);
                    }
                }

                return true;
            });
```

**Comment by marcelogarbin** [comment]
Wow that's cool, very good to exchange experience with other devs this way (from other places in the world hehe). :smile:

I believe my questions have been answered, I will close this issue.

Thanks for your attention.

Best regards
