### ISSUE TITLE
Two active routes error

### ISSUE THREAD

**Issue by RERE110** [lavary/laravel-menu#269]
Hello,

I am a little confused by an event. Indeed when I use the "ACTIVE" option my menu activates well, but only it activates another element in my menu which has nothing to do.

In reality your package detects two active routes.
This only happens on one route.

I would like to try to move the project forward.
I'm putting you screens.
<a href="https://zupimages.net/viewer.php?id=20/18/jarb.jpg"><img src="https://zupimages.net/up/20/18/jarb.jpg" alt="" /></a>

<a href="https://zupimages.net/viewer.php?id=20/18/cj8a.jpg"><img src="https://zupimages.net/up/20/18/cj8a.jpg" alt="" /></a>

Looks,

**Comment by dustingraham** [comment]
Without seeing any code, I would guess that you might be auto-activating a route based on the current page URL. But, then you might be manually activating a route as well.

If that doesn't help, can you provide a simplified code example that I can use to see the issue.

**Comment by RERE110** [comment]
> Without seeing any code, I would guess that you might be auto-activating a route based on the current page URL. But, then you might be manually activating a route as well.
> 
> If that doesn't help, can you provide a simplified code example that I can use to see the issue.

Thank you for your reply,

Here are my different files that I use


My config file.

```php
return array(
    'default' => array(
        'auto_activate' => true,
        'activate_parents' => true,
        'active_class' => 'active',
        'restful' => false,
        'cascade_data' => true,
        'rest_base' => '',      // string|array
        'active_element' => 'item',  // item|link
    ),
);
```

My blade file.
```php
@foreach($items as $item)
    <li @lm_attrs($item) @lm_endattrs>
        @if($item->hasParent() === true)
            <a href="{!! $item->url() !!}">
                <i class="fa fa-circle"></i>
                <span style="text-transform: none">
                    {!! $item->title !!}
                </span>
            </a>
        @else
            <a class="sidebar-header" href="{!! $item->url() !!}">
                <i data-feather="{!! $item->data('icon') !!}"></i>
                <span style="text-transform: none">
                    {!! $item->title !!}
                </span>
                @if($item->hasChildren())
                    <i class="fa fa-angle-right pull-right"></i>
                @endif
            </a>
        @endif
        @if($item->hasChildren())
            <ul class="sidebar-submenu">
                @include('platform.layouts.menu', ['items' => $item->children()])
            </ul>
        @endif
    </li>
@endforeach
```

Thank you

**Comment by dustingraham** [comment]
It looks like you set auto_activate to true, and activate_parents to true.

If you're manually activating another route, then that will cause two activations.
