### ISSUE TITLE
settings.php file need to be moved in config folder

### ISSUE THREAD

**Issue by iivanov2** [lavary/laravel-menu#271]
The settings.php file needs to be moved in the main config folder of the app or we need another method to override the default settings without changing them in vendor folder according to SOLID.

I will try to extend the service provider in order to override the settings.php path.

**Comment by iivanov2** [comment]
OK I have understand it, I need to create config/laravel-menu/settings.php file and to write my settings there, please add this to documentation it would be useful.

**Comment by dustingraham** [comment]
This is in the documentation under Installation.

To use your own settings, publish config.

`php artisan vendor:publish --provider="Lavary\Menu\ServiceProvider"`
