### ISSUE TITLE
Default settings config for data_toggle_attribute is incorrectly using kebab-case instead of snake_case

### ISSUE THREAD

**Issue by theeie** [lavary/laravel-menu#283]
https://github.com/lavary/laravel-menu/blob/4ae8ae803e9de14e56f9bb671071770b3e6cfe17/src/config/settings.php#L12
Shouldn't this be "data_toggle_attribute" rather than "data-toggle-attribute"?

From my limited testing changing it to the snake_case format "data_toggle_attribute" fixed an issue where the generated dropdowns didn't work properly.

**Comment by dustingraham** [comment]
Thanks corrected with 8c63065d128809133df4f5e79e88e5c50715126e
