### ISSUE TITLE
BUG active link. Forced https

### ISSUE THREAD

**Issue by ghost** [lavary/laravel-menu#294]
When forced https is added, css active classes on links are no longer added.

app/Providers/AppServiceProvider.php
`public function boot()
    {
        \Illuminate\Support\Facades\URL::forceScheme('https');
    }`

**Comment by dustingraham** [comment]
I have not validated this error, but if someone wants to validate and PR, I can review it.

**Comment by ghost** [comment]
I solved this by setting up the:
`\Illuminate\Support\Facades\URL rule in the provider::force Scheme('https');`

**Comment by dustingraham** [comment]
I don't understand what you mean by that. Should we close this issue then if it is solved? Or are you saying that's the solution that someone needs to write a PR for?

Thanks.

**Comment by ghost** [comment]
I found this solution after I wrote the question, yes, you can close it, thank you!
