### ISSUE TITLE
Passing null to parameter #1 ($string) of type string is deprecated .. Menu/Builder.php on line 303 (LF 10 / PHP 8.1)

### ISSUE THREAD

**Issue by jirapetr** [lavary/laravel-menu#304]
In Laravel 10/PHP 8.1
 LOG.warning: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/foo/vendor/lavary/laravel-menu/src/Lavary/Menu/Builder.php on line 303

problematic part of code in PHP 8.1:
`trim(trim(Arr::get($old, 'class')).' '.trim(Arr::get($new, 'class')));`

**Comment by mgralikowski** [comment]
It is [fixed](https://github.com/lavary/laravel-menu/pull/291) but only on the master branch.

`"lavary/laravel-menu": "dev-master"`

**Comment by dustingraham** [comment]
Published https://github.com/lavary/laravel-menu/releases/tag/v1.8.4
