### ISSUE TITLE
Unique title overriding

### ISSUE THREAD

**Issue by MattWohler** [lavary/laravel-menu#35]
``` php
$menu->add('Companies', 'companies');
$menu->companies->add('New', 'companies/new');
$menu->companies->add('All', 'companies/all');

$menu->add('Users', 'users');
$menu->users->add('New', 'users/new');
$menu->users->add('All', 'users/all');

$menu->all->link->['foo' => 'bar']);
```

The title property is used to define the item object.

In the above use case, the item's link attribute is setting for both companies->all and users->all.

Is this intended, a bug, or am I blatantly missing something?

**Comment by dustingraham** [comment]
Item now has a unique id value.
