### ISSUE TITLE
Location of setting up your menu

### ISSUE THREAD

**Issue by afraca** [lavary/laravel-menu#38]
Hey, 

Nice work on this package! One thing is a bit odd though. The readme advices people to include the setting up of your menu in your `routes.php` or in `global.php` , but to me that sounds like overkill. It seems to me this would be slightly better: 

If you have some master template, put in the top 

    <?php require app_path() . '/views/menubuilder.php'; ?> 

There you build your menu. This way you won't unneccesarily pollute API calls with your menu building which you'll never use in those calls.

**Comment by icfr** [comment]
another way is to put it in a middleware and call it in the controller construction or in the route construction
```
 public function __construct()
 {
        $this->middleware('menu');
 }
```

**Comment by vedmant** [comment]
I've come up with using middleware for menu configuration as I only can read session data from middleware, on applications booting up session is not started.

**Comment by lavary** [comment]
Using a middleware seems to be the best option in L5. I'll update the documentation.

Thanks.
