### ISSUE TITLE
Incorrect Syntax in doccumentaion page

### ISSUE THREAD

**Issue by TickledPink** [lavary/laravel-menu#39]
hey, i think you miss write the docs page at prefixing

so here is the code

<?php
Menu::make('MyNavBar', function($menu){

  $menu->add('Home',     array('route'  => 'home.page', 'class' => 'navbar navbar-home', 'id' => 'home'));

  $menu->add('About', array('url'  => 'about', 'class' => 'navbar navbar-about dropdown'));  // URL: /about 

  $menu->group(array('prefix' => 'about') function($m){

    $about->add('Who we are?', 'who-we-are');   // URL: about/who-we-are
    $about->add('What we do?', 'what-we-do');   // URL: about/what-we-do

  }

  $menu->add('Contact',  'contact');

});
?>

and it should be

<?php
Menu::make('MyNavBar', function($menu){

  $menu->add('Home',     array('route'  => 'home.page', 'class' => 'navbar navbar-home', 'id' => 'home'));

  $menu->add('about', array('url'  => 'about', 'class' => 'navbar navbar-about dropdown'));  // URL: /about 

  $menu->group(array('prefix' => 'about'), function($m){

    $m->about->add('Who we are?', 'who-we-are');   // URL: about/who-we-are
    $m->about->add('What we do?', 'what-we-do');   // URL: about/what-we-do

  });

  $menu->add('Contact',  'contact');

});
?>

thank you

**Comment by lavary** [comment]
Updated! 
Thanks :)
