### ISSUE TITLE
Specify the id of the item manually

### ISSUE THREAD

**Issue by feralc** [lavary/laravel-menu#42]
Would be interesting to set the id of the item manually, it would facilitate the creation of submenus using the method find, so for example, I could set the id of the item by the same id of a record in a database table.

For example:

$menu->add("Item title", "Item ID", $options);

In this case the id of the item could be optional, if not passed, would be set automatically as currently occurs.

**Comment by dustingraham** [comment]
Might help fix #35

**Comment by paumove** [comment]
+1

**Comment by lavary** [comment]
You can use the `id()` method, which has been added to the package in the latest release.

```php
<?php
 //...
$menu->add('Home', 'home')->id(34567654);

// or

$menu->add('Home', ['url' => 'home', 'id' => 34567654]);

//...

**Comment by lavary** [comment]
Closing the issue. Feel free to reopen if you face a problem.
