### ISSUE TITLE
Error add menu with action

### ISSUE THREAD

**Issue by ThemeRevolution** [lavary/laravel-menu#44]
I tried to add menu with action but always return Exception with message "Route [HomeController@getIndex] not defined." though its already defined.

This problem occurs when I put menu definition outside routes.php, I put it in app/menus.php which actually loaded by start/global.php

**Comment by arall** [comment]
Same problem here.

**Comment by dustingraham** [comment]
Is this still a problem? Have you tried the latest version? Is your `app/menus.php` running before the routes are defined?

**Comment by lavary** [comment]
You may have your menus defined in a global middleware. Please read the updated documentation.

**Comment by lavary** [comment]
Closing the issue. Feel free to reopen if you face a problem.
