### ISSUE TITLE
Facade not working

### ISSUE THREAD

**Issue by webal** [lavary/laravel-menu#45]
I've installed the latest package (using composer), and have added the service provider and facade as per the docs (including to my local config file. When I run the following code, I get the error listed below:

        Menu::make('MyNavBar', function($menu){
          $menu->add('Home',     array('route'  => 'home.page'));
        });

error:

      Non-static method Lavary\Menu\Menu::make() should not be called statically, assuming $this from incompatible context 

The error links to the first line of the code above.

It seems that the facade isn't working quite like it should, I've had a look but I'm not familiar enough with creating facades to see an issue.

I'm working on windows/WAMP if that makes any difference?

**Comment by fabioi** [comment]
same error? has anyone solved the problem?

**Comment by fabioi** [comment]
same error here. Has anyone solved the problem?

**Comment by webal** [comment]
I'm afraid to say I gave up trying to use the package because of this and another issue :(

**Comment by fabioi** [comment]
I am stuck too with this plugin, thanks very much for your reply!

**Comment by lavary** [comment]
@webal  Hi, sorry for the extremely late reply.
The message implies that the facade class is not working as expected.
Can you check if you've got also another alias named `Menu` in `aliases` array? There might be some collisions in the array.
You may want to change the alias name temporarily from `Menu` to `Lmenu` for example and call `Lmenu::make` and see what you get.

**Comment by webal** [comment]
Hi, thanks for the reply I've taken it out of my project now because of the issues I had with this and the config.
I did, however, try to instantiate the class directly in the code where I used it (rather than relying on a facade) and this also failed. I'm afraid I don't remember exactly what errors this threw and the code is long gone now.

**Comment by tcrawf** [comment]
I am a bit late to the party, but the definition of the prepend function in Collection.php is using the laravel 5.0 api. I updated the prepend function in Collection.php to include the key parameter. All is working for me. 
```
/**
	 * Prepends text or HTML to a collection of items
	 *
	 * @param  string  
	 * @return Lavary\Menu\Collection
	 */
	public function prepend($html,$key=null) {
		
		$this->each(function($item) use ($html){
			$item->title = $html . $item->title;
		});
		
		return $this;
	}

/**
	 * Prepends text or HTML to a collection of items
	 *
	 * @param  string  
	 * @return Lavary\Menu\Collection
	 */
	public function prepend($html,$key=null) {
		
		$this->each(function($item) use ($html){
			$item->title = $html . $item->title;
		});
		
		return $this;
	}
```

**Comment by gamunuud** [comment]
Hi,

If anyone still having this issue maybe because you are directly using the class `Lavary\Menu\Menu`, you'll need to use the facade if you wan't to call method statically `use Lavary\Menu\Facade as Menu;`

**Comment by ZN00** [comment]
Thanks @gamunuud, with this no have that problem

**Comment by xshagg** [comment]
Jst create an object
```
$menu = new Menu;
$menu->make('LeftPane', function ($menu) {
	$menu->add('Home');
	$menu->add('About', 'about');
	$menu->add('services', 'services');
	$menu->add('Contact', 'contact');
});
```
Menu::make() cannot be used statically because there is non-static collection:
```
class Menu {
	...
	protected $collection;
	...
	public function make($name, $callback)
	{
		...
			// Storing each menu instance in the collection
			$this->collection->put($name, $menu);
		...

```
