### ISSUE TITLE
Config file issues

### ISSUE THREAD

**Issue by webal** [lavary/laravel-menu#46]
After hitting issues with the facade (https://github.com/lavary/laravel-menu/issues?q=is%3Aopen+is%3Aissue) I tried calling the the code below and received an error. I've seen similar errors in the past which has been down to Laravel having issues with multiple config files (on certain systems at random). The package/service provider/facade are all installed as per the docs, I'm running windows/WAMP. 

My code:

        $menu = new Menu;
        $menu->make('MyNavBar', function($menu){
          $menu->add('Home',     array('route'  => 'home.page'));
        });

The error:

    Undefined index: default 
    here: …\vendor\lavary\laravel-menu\src\Lavary\Menu\Menu.php 63

It seems as though the config is not loading, I've tried dumping the $options array from a line 56 in Menu.php and this returns:
 
     array (size=0)
        empty

**Comment by primerg** [comment]
Experienced this too today. Add this in the register() in the ServiceProvider
`` $this->app['config']->package('lavary/laravel-menu', __DIR__.'/../../config'); ``

I forked to add this change:
https://github.com/primerg/laravel-menu/blob/8a879073830ee6ef1651ff8f23b2182a1bef1daf/src/Lavary/Menu/ServiceProvider.php

**Comment by lavary** [comment]
lavary/laravel-menu 1.5.3 has been released supporting Laravel 5.1.

**Comment by lavary** [comment]
Closing the issue, please feel free to re open if you encounter any problem.
