### ISSUE TITLE
New Menu Layout

### ISSUE THREAD

**Issue by kgmahn** [lavary/laravel-menu#50]
It would be nice to have the ability to show the menu horizontal. I have an application that I am rewriting in Laravel and need to have the menu go across the top. The menu system I have uses a hidden table for the layout but there maybe a better way to do it. I looked at doing it using CSS but with the list tags, I am not sure how a horizontal menu would work.

Regards,
Ken

**Comment by enigmatic-user** [comment]
Do yourself a favor and don't use tables for that (or anything that is just layout). That's what CSS is for.

Basically you have to "float" the list items. You'll find a very basic and easy to follow tutorial on http://www.w3schools.com/css/css_navbar.asp. But the web is full of tutorials for things like this - just give the search engine of your choice a chance!  :)

**Comment by lavary** [comment]
You can use Bootstrap for rendering the menu a horizontal navigation bar. The package provides a Bootstrap based view out of the box.

```html
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

       @include(Config::get('laravel-menu::views.bootstrap-items'), array('items' => $mainNav->roots()))

      </ul>
      <form class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
```
 


It is fully covered in the documentation: (Menu as Bootstrap 3 Navbar)[https://github.com/lavary/laravel-menu#menu-as-bootstrap-3-navbar]

If you don't want to use Bootstrap, the example should give the idea of building a horizontal navigation bar.

**Comment by lavary** [comment]
Closing the issue, please feel free to reopen if needed.
