### ISSUE TITLE
Build breadcrumbs based on active path

### ISSUE THREAD

**Issue by psheiman** [lavary/laravel-menu#51]
Hello, and thanks you for such great packaged!

But I can't find any easy way to build breadcrumbs based on active path. 

Let's say we have following menu structure:

```php
$menu->add('Dashboard', ['action' => 'DashboardController@showDashboardPage']);

$menu->add('Push Notifications');
$menu->pushNotifications->add('Overview', ['action' => 'Controller@ActionA']);
$menu->pushNotifications->add('Create Campaign', ['action' => 'Controller@Action B']);
```

So I want to build breadcrubms like so:

* When on dashboard page: `Home > Dashboard`.
* When on overview page: `Home > Push Notifications > Overview`.
* When on create campaign page: `Home > Push Notifications > Create Campaign`.

I'm pretty sure I've read all documentation, but I can't find how to do this right now. Is this possible?

**Comment by lavary** [comment]
Hi, sorry for the extremely late reply. I'm afraid the package doesn't generate breadcrumbs at the moment. 

(laravel-breadcrumbs)[https://github.com/davejamesmiller/laravel-breadcrumbs] would be a good one to try.

**Comment by lavary** [comment]
Closing the issue, please feel free to reopen it if needed.
