### ISSUE TITLE
L5 compatibility

### ISSUE THREAD

**Issue by fredrkr** [lavary/laravel-menu#52]
Are there any plans to make this package compatible with L5? (Assuming it's not already)

**Comment by gbrock** [comment]
+1

**Comment by sdbruder** [comment]
+1

**Comment by alexey-fut** [comment]
+1

**Comment by nickurt** [comment]
See #54

**Comment by mnewmedia** [comment]
+1

**Comment by xsen** [comment]
+1

**Comment by Fuhrmann** [comment]
+1

**Comment by TheDeadCode** [comment]
+1

**Comment by stojankukrika** [comment]
+100

**Comment by TheDeadCode** [comment]
From what I've seen I only had to do very minor changes for it to work. I'll fork this repo and make an update on how to do it. Cheers!

**Comment by vinicius73** [comment]
Please update the documentation

**Comment by ilkermutlu** [comment]
Seems like there are already 3 pull requests for L5 compatibility. 

Will the author merge one of those?

**Comment by mouhsinelonly** [comment]
+1

**Comment by ali997** [comment]
+1

**Comment by iffifan** [comment]
+1

**Comment by naysumyat** [comment]
+1

**Comment by MegaSniperB** [comment]
+1

**Comment by lavary** [comment]
lavary/laravel-menu 1.5.1 has been released supporting Laravel 5.1.

master branch has the latest changes.

**Comment by lavary** [comment]
Closing the issue, please feel free to re open if you encounter any problem.
