### ISSUE TITLE
How do i know the item is active in my custom menu blade?

### ISSUE THREAD

**Issue by miaotaizi** [lavary/laravel-menu#62]
Hi @lavary  , thx for your package.
When i use my custom menu blade, how to know the item is active?
I need to add some active class in html.
Forgive my broken english. :cry:

**Comment by dawid-z** [comment]
Firstly, publish config files:
```
php artisan vendor:publish
```
now add your classes to `config/laravel-menu/settings.php`
```
<?php
return array(
	'default' => array(
                ...
		'active_class'     => 'active' // <= here
                ...
	)
);

**Comment by dustingraham** [comment]
Let me know if @dawid-z  solution doesn't work for you.

**Comment by mitjarobic** [comment]
how do u check if the item is acitve when using custom template?
