### ISSUE TITLE
Many inconsistencies

### ISSUE THREAD

**Issue by Wmas** [lavary/laravel-menu#64]
I was looking for a menu for Laravel 5 and I found this one.
Unfortunately the documentation and the branches do not match, so after a few hours making this work I had to quit.
Can anyone point me to the correct installation for the latest updated and working package?
I also want to encourage you to review the documentation because many of the examples do not work (anymore), and this will confuse of course everyone wanting to use it.

This will be a pity, seen the work has been made to develop it

Any help will be appreciated.

Cheers

Franco

**Comment by lavary** [comment]
The new version of lavary/laravel-menu has been released supporting Laravel v5.1.

**Comment by lavary** [comment]
Closing the issue, please feel free to re open if you encounter any problem.
