### ISSUE TITLE
ErrorException in Builder.php line 577 : Array to string conversion

### ISSUE THREAD

**Issue by Saradimi** [lavary/laravel-menu#67]
Hi, 
I'm trying to create a menu, according to the documentation, but always obtain the following error : "Array to string conversion" when i'm trying to print it on the view.
I tried to access the menu with the asUl method  {!! Menu::get('MyNavBar')->asUl() !!}  and with the custom menu template in a separate view but always got this issue.
Laravel version is 5.1.
A little help would be appreciated :)
Thank in advance.

**Comment by lavary** [comment]
I updated the code, this was due to a recent change in the Builder script. You may update the package to see if it works.

By the way thanks for using the package :)

**Comment by Saradimi** [comment]
Works perfectly now !
Thank a lot for this great package.

**Comment by EselDompteur** [comment]
After this was fixed i got an Exeption Error in Item.php cause Laravel was unable to find the Method Str() used in Line 77 ..

I have fixed this by correct the use statement in item.php from

use Str; 
to

use Illuminate\Support\Str;

... hope this could anyone help.

**Comment by ArtemProkopenko** [comment]
It isn't fixing for 1.5.1 version. 
And for last version (dev-master) here is error described above.

Ultimately, now there isn't working version for Laravel 5 =/

**Comment by KayCreations** [comment]
You can also fix this by adding "'Str' => Illuminate\Support\Str::class" to the config/app.php. This is much better as hack it into into the code...

**Comment by Dreanmer** [comment]
Same error, latest (1.5.1) release, laravel 5.1

````
ErrorException in Builder.php line 557:
Array to string conversion
