### ISSUE TITLE
Composer Update Laravel 4.2 Problem

### ISSUE THREAD

**Issue by lazos99** [lavary/laravel-menu#68]
Generating autoload files
{"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","message":"Call to undefined method Lavary\\Menu\\ServiceProvider::mergeConfigFrom()","file":"C:\\xampp\\htdocs\\nanolarave
l\\vendor\\lavary\\laravel-menu\\src\\Lavary\\Menu\\ServiceProvider.php","line":21}}Script php artisan clear-compiled handling the post-update-cmd event returned with an error

**Comment by george1974** [comment]
Facing similar composer update problem:

Generating autoload files
PHP Fatal error:  Call to undefined method Lavary\Menu\ServiceProvider::mergeConfigFrom() in /var/www/project/vendor/lavary/laravel-menu/src/Lavary/Menu/ServiceProvider.php on line 21
{"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","message":"Call to undefined method Lavary\\Menu\\ServiceProvider::mergeConfigFrom()","file":"\/var\/www\/project\/vendor\/lavary\/laravel-menu\/src\/Lavary\/Menu\/ServiceProvider.php","line":21}}Script php artisan clear-compiled handling the post-update-cmd event returned with an error

**Comment by lazos99** [comment]
I think the problem is that they updated the ServiceProvider to support some kind of configuration changes for Laravel 5.1 but they do not exist in 4.2. I hope the developer can create a different repo just for Laravel 4.2.

**Comment by george1974** [comment]
You are right. Awaiting for changes as I have no plans to migrate to Laravel 5 anytime soon.

**Comment by driesvancraen** [comment]
Same problem here.

**Comment by jake-harris** [comment]
Was able to revert by updating `composer.json` to use the pre-"5.1 commit" version : 
````
...
"require": {
    "laravel/framework": "4.2.16",
    ...
    "lavary/laravel-menu": "dev-master#230c49575b8d549c139088ea67555213c9e39256"
}
...
````

You could always use v 1.5.0 as well.

**Comment by dustingraham** [comment]
Same issue here. I would love to update, but will be a massive project when the time is available. 4.2 for a while.

Thanks jake-harris! I'll give it a shot.

**Comment by lexilya** [comment]
In my opinion, that should have been at least a 1.6 (or possibly 2.0) release, as it breaks on all old projects.

**Comment by dustingraham** [comment]
I think moving to Laravel 5 should have been 2.0 absolutely. :)

**Comment by davidcantwell** [comment]
I just ran in to this problem as well updating my project.  Thanks jake-harris - that fix worked for me as well.

**Comment by lexilya** [comment]
Be aware that it's broken again after yesterday's change to composer.json, since locking to a specific commit does not use the composer.json of that commit.

**Comment by lexilya** [comment]
Locking it to a specific tag is still fine, though. e.g. like  "lavary/laravel-menu": "1.5.0". Just don't add ~, since 1.5.1 is broken in 4.2.

**Comment by jake-harris** [comment]
Good call, lexilya. I updated my comment above.

**Comment by dustingraham** [comment]
As @jake-harris and @lexilya  pointed out, please use 1.5.0 for laravel 4.2
