### ISSUE TITLE
Add "Active" function from pattern in the 1.4.x branch

### ISSUE THREAD

**Issue by Dimidel** [lavary/laravel-menu#71]
I Lavary,
I noticed that you have extended the "active" function with the pattern recognition but you've done that only for the master branch which is only compatible with Laravel 5.
Could you please add this possibility to the 1.4 branch for the Laravel 4 users ?
Thanks for your great job and sorry for my broken english.

**Comment by adamriggsy** [comment]
I would second this. It would be awesome to have this functionality in 4.2 as well. Thanks for considering.

**Comment by dustingraham** [comment]
Unless someone wants to make a PR, I don't expect we'll be updating for laravel 4.2. Closing for now.
