### ISSUE TITLE
Array to string conversion Error

### ISSUE THREAD

**Issue by vedmant** [lavary/laravel-menu#74]
Hi, when I'm trying to add menu to view I'm getting this error:
Array to string conversion in /vendor/lavary/laravel-menu/src/Lavary/Menu/Builder.php line 557

here is my code:

    Menu::make('menu_front', function ($menu) {
    
        $menu->add('Login', 'login');
        if(Auth::check() && Auth::user()->isAdmin()) $menu->add('Admin', 'admin');
    
    });

and

    {!! Menu::get('menu_front')->asUl() !!}

or

    {!! $menu_front->asUl() !!}

I use latest version 1.5.1 and laravel 5.1.10

PS: Laravel from v5.1 moved to spaces indents, I think it's good to change coding style here as well.

**Comment by andrzejkupczyk** [comment]
I have the same problem.

**Comment by lavary** [comment]
i'm closing the issue since it has been fixed in the latest release.

**Comment by jonnylor63** [comment]
sure to use "lavary/laravel-menu": "dev-master" in composer.json
