### ISSUE TITLE
How do i Modify/Update the item?

### ISSUE THREAD

**Issue by khensolomon** [lavary/laravel-menu#77]
I could not find a way to update the attributes according to Auth:user().
In routes.php there is no value return for "Auth:user()" and I do not want to call "Menu::make" in every Controllers.
eg. When a user is already logged in, I certainly do not want to show the login link.

**Comment by mms-hamburg** [comment]
look at this https://github.com/lavary/laravel-menu#filtering-the-items
you can do a function(){ return !Auth::check() }  for example

**Comment by khensolomonlethil** [comment]
Yes I tried! The Auth::guest() return true and Auth::check() return NULL even the user is logged in... My guess is that the routes.php is not a proper place for Menu::make(), so I create a new middleware for Menu::make()... still I am not happy calling this method every times on like ajax or api access...

Also there is one more issue for adding child:
```
<?php
Menu::make('MyNavBar', function($menu){
	/*
		What... if I like to use $:Variable instead of text:"Users"
	*/
	$menu->add('Users', 'users');
	$menu->users->add('New User', 'users/new');
	/*
		Hum... this is not gonna work!
	*/
	$menu->add($Username, 'users');
	$menu->$Username->add('Update Password', 'update-password');
	/*
		Bad idea... seem like a php programmer from 98's
	*/
	$menu->add('a1', 'users');
	$menu->a1->add('Update Password', 'update-password');
	$menu->a1->title=$Username;
});
?>
```
This looks very bad. If you have a better idea please help me...

**Comment by lavary** [comment]
The best option is currently to define your menus inside a middleware.

**Comment by khensolomonlethil** [comment]
Yes, it's to be inside a middleware, I agreed!
```
<?php
Menu::make('MenuUsers', function($menu){
    $menu->add('Users', array('route'  => 'just.users'))->data('permission', 'manage_users');
    $menu->add('Manager', array('route'  => 'manager.users'))->data('permission', 'manage_users');
    $menu->add('Admin', array('route'  => 'admin.users'))->data('permission', 'admin_users');
    /*
        Now the problem here is, the filter only **RETURN** one just for **TRUE** OR **FALSE**
    */
    })->filter(function($item){
        if(User::get()->can( $item->data('permission')))return true;
        return false;
});
?>
```
It would be nice, if the filter check each $menu row's and then granted according to each rows permission! Or how do we check each rows permission?

**Comment by lavary** [comment]
Sorry, would you please explain more clearly. To me your code should work as expected. Instead of a user model, I put the permissions inside an array, just for the testing purpose. Then inside the `filter` I check for the existence of the permission in side the array:

```php
<?php
$perms = ['just_users', 'manage_users', 'admin_users'];

Menu::make('main', function($m){
    
    $m->add('Users',   'users')        ->data('permission', 'just_users');
    $m->add('Manager', 'manage-users') ->data('permission', 'manage_users');
    $m->add('Admin',   'admin-users')  ->data('permission', 'admin_users');
   
})
->filter(function($item) use ($perms){
    if( in_array($item->permission, $perms) ) {
        return true;
    } 

    return false;
});
```

**Comment by lavary** [comment]
As a result all the items are returned. If you eliminate a permission from the array, you wont get that specific menu item. Am I missing something here?

**Comment by khensolomonlethil** [comment]
Hei Lavary!
Sorry for my english! but you understood it well! I've test... and **It work**... *hehe*

The problem was: where I check the "User Authentication" return the user role id, and the Menu item permission await for string!

Thank you so much Lavary, the filter problem is totally solved for me now.

As for another question! How do we actually **append Menu item** from outside the **Menu::make**?

**Comment by lavary** [comment]
i'm glad you sort it out.

Regarding your question, you can do it like so:

```php
<?php
 Menu::get('MenuUsers')->add('Another item');
```

For example to add a submenu item to `Admin`, you can:

```php
<?php
Menu::get('MenuUsers')->admin->add('Admin sub');
```

Hope that helps.

**Comment by khensolomonlethil** [comment]
Yes it help me... But unfortunately the Menu Item Name/Title, where I did like to append has to be Variable... say a ```$Username```;

**Comment by lavary** [comment]
You will just need your menu name:

```php
<?php
$username = 'Me';
Menu::get('MenuUsers')->add($username);
```

or for adding a submenu which both parent and child are dynamic:

```php
<?php

$parent = 'admin';
$username = 'Me';
Menu::get('MenuUsers')->get($parent)->add($username);
```
