### ISSUE TITLE
Set active_element on both elements

### ISSUE THREAD

**Issue by paumove** [lavary/laravel-menu#80]
It would be nice to have the option of setting the parameter 'active_element' with the value 'both'. In some templates you need to set the 'active' class in both the link and the item.

One suggested solution might be on Item.php, activate method:

if( $this->builder->conf('active_element') == 'item' )
{
    $item->active();
}
else if( $this->builder->conf('active_element') == 'both' )
{
    $item->active();
    $item->link->active();
}
else
{
    $item->link->active();
}

**Comment by dustingraham** [comment]
Not saying this isn't a good idea, but regarding the concept, if you set the active element on the parent, can't you do li.active > a { } to target the child element? I understand you're using a theme, but would this be a reasonable thing to add into an override.less file?

**Comment by paumove** [comment]
You're right, I think it's a bad management by the template menu. As you have suggested, I have been solved through css and setting active element on link. I had been thinking that the solution was to apply style to the parent element, but css can't do this.

This is how the template displays the menu. In the main menu it puts the "active" in anchor and in the submenu puts the "active" on list item.

<ul class="sidebar-menu" id="nav-accordion">
	<li>
		<a href="index.html">
			<span>Dashboard</span>
		</a>
	</li>
	<li class="sub-menu dcjq-parent-li">
		<a href="javascript:;" class="active dcjq-parent">
			<span>Layouts</span>
		</a>
		<ul class="sub" style="display: block;">
			<li class="active">
				<a href="boxed_page.html">Boxed Page</a>
			</li>
			<li>
				<a href="horizontal_menu.html">Horizontal Menu</a>
			</li>
		</ul>
	</li>
</ul>

Thanks for your help. Great job with this addon.
