### ISSUE TITLE
Class 'App\Http\Middleware\Menu' not found

### ISSUE THREAD

**Issue by eschmid72** [lavary/laravel-menu#81]
In your documentation you write:

"You can define the menu definitions inside a laravel middleware.".

Well, I tried it:

```php
<?php

namespace App\Http\Middleware;
use Closure;
//use Lavary\Menu\Menu;

class Frontend
{
    public function handle($request, Closure $next)
    {

        Menu::make('NavBarLeft', function($menu){

            $menu->add('Home', ['route' => 'page.home']);
            $menu->add('Test', ['route' => 'page.test']);

        });
        return $next($request);
    }
}
```

But I'm getting the Exception: Class 'App\Http\Middleware\Menu' not found
What's missing in my code? Please add an example in your readme.md.

**Comment by lavary** [comment]
Sorry for the late response. Your namespace is `App\Http\Middleware`. That's the reason the script looks for the menu in this namespace. You can simply use add backslash to the menu class to resolve the issue:

```php
<?php
//...

\Menu::make('NavBarLeft', function($menu){

            $menu->add('Home', ['route' => 'page.home']);
            $menu->add('Test', ['route' => 'page.test']);

        });

// ...
```

**Comment by lavary** [comment]
I will add an example in the `readme.md`

**Comment by lavary** [comment]
Closing the issue. 

feel free to reopen, if you have any other problem.

**Comment by windhorst** [comment]
I'm having the same issue but I do have the backslash in front of Menu::make. Anymore thoughts on what might cause this?  I have removed it and reinstalled it but no luck.

```
\Menu::make('PublicMenu', function($menu){
            $menu->add('Login');
            $menu->add('Features',    'about');
            $menu->add('services', 'services');
            $menu->add('Contact',  'contact');
        });
```
