### ISSUE TITLE
rtl language support

### ISSUE THREAD

**Issue by saeedvaziry** [lavary/laravel-menu#84]
~~~
$menu->add('سهنپ')->add('درباره ما','about')->data('icon','info');
$menu->item('سهنپ')->add('افقهای سهنپ','horizon');
~~~
this shows : 
~~~
Call to a member function add() on a non-object
~~~

**Comment by amin101** [comment]
no its not right way of implementing menu by your native language. I think you should use `trans() `function in blade.

**Comment by saeedvaziry** [comment]
thanks

**Comment by lavary** [comment]
You can use `nickname()` method, which has been added to the package in the latest release.

**Comment by lavary** [comment]
Closing the issue, feel free to reopen if you face a problem.
