### ISSUE TITLE
Collection error "Getting Started"

### ISSUE THREAD

**Issue by repeater09** [lavary/laravel-menu#88]
I am trying to get started with laravel-menu. I set everything up in app/config.php. When I go to load the page the MyNavBar example:

`<?php
Menu::make('MyNavBar', function($menu){

  $menu->add('Home');
  $menu->add('About',    'about');
  $menu->add('services', 'services');
  $menu->add('Contact',  'contact');

});
?>`

I get the following error:

`Declaration of Lavary\Menu\Collection::prepend() should be compatible with Illuminate\Support\Collection::prepend($value, $key = NULL)`

I am using 5.1 if that helps.

**Comment by repeater09** [comment]
I had to add `$key=NULL` as the second parameter in Collections.php line 78 and that seemed to do the trick. I am using I believe 5.1.27. Maybe Collection changed?

**Comment by mouhsinelonly** [comment]
i think this should be updated very soon

**Comment by uyab** [comment]
Should have been fixed by this PR: https://github.com/lavary/laravel-menu/pull/87
