### ISSUE TITLE
Define menu items in a context different from Routes.php

### ISSUE THREAD

**Issue by npedrocco** [lavary/laravel-menu#89]
I need to create menu items somewhere else from Routes because in that context I don't have full access to the Auth::user()->locale object, which contains user configuration which in turn shall translate the labels of the menu items to the desireg language.

So I was wondering if it's possible to fetch items in a different way and how, to bypass the problem.

Thanks a lot!

**Comment by lavary** [comment]
You can create a middleware to define your menus.

To create the middleware, while in your project directory, run the following command:

```bash
php artisan make:middleware MenuMiddleware
```

Then go to `app/Htpp/Middleware` directory, and define your menu items in `MenuMiddleware.php`  file:

```php
<?php

namespace App\Http\Middleware;

use Closure;

class Menu2Middleware
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        \Menu::make('MainMenu', function($m) {
            
            $m->add('Item 1', 'item-1-url');
            $m->add('Item 2', 'item-2-url');
            $m->add('Item 3', 'item-3-url');
            
        });

        return $next($request);
    }
}
```

**Comment by npedrocco** [comment]
Works like a charm! Also, menu in middleware makes more sense to me than in routes :)

Thanks

**Comment by amin101** [comment]
I'm a little suspicious to this method. say we are sending a POST request  or using AJAX.
Is it really necessary to call this Middleware each time we have an interaction with app?

**Comment by lavary** [comment]
@amin101 You can use route middlewares, meaning assigning the middleware to a route or a group of routes.

**Comment by ivanhalen** [comment]
Can I also wrap the `Menu::make()` in a `if ($request->isMethod('get')){ ... }` statement to exclude POSTs requests and gain some performance? (sorry for the very newbie question...)
