### ISSUE TITLE
Issue with divider

### ISSUE THREAD

**Issue by nycofox** [lavary/laravel-menu#90]
There's an issue with the divider in **src/Lavary/Menu/resources/views/bootstrap-navbar-items.blade.php**

Should be like this:

`<li{!! Lavary\Menu\Builder::attributes($item->divider) !!}></li>`

Only one `{` and `}`, not two.

**Comment by lavary** [comment]
Thanks for reporting the issue. It's been fixed.

Thanks :+1:
