### ISSUE TITLE
Add attr's like ID and CLASS to children "ul".

### ISSUE THREAD

**Issue by rafaelbazanella** [lavary/laravel-menu#92]
``` php
$sistema = $menu->add('Sistema',    array('url'  => '#sub-item-1', 'class' => 'parent'))
                ->append('<i class="fa fa-cogs"></i>')
                ->prepend('<i class="fa fa-sort-desc pull-right" style="margin-top: -3px;"></i>');
 // LINK attr
 $sistema->link->attr(array('data-toggle' => 'collapse'));


 $menu->sistema->add('Usuário', array('action'  => 'UsuarioController@index'))
                ->append('<i class="glyphicon glyphicon-user"></i>');
```

**THE CODE ABOVE WILL GENERATE:**

``` html
<li>
    <a></a>
    <ul> <!-- NEED TO PUT ATTR's HERE :( -->
        <li></li>
    </ul>
</li>
```

Sorry for English, i'm from BR.

**Comment by delatbabel** [comment]
This request is the only thing that prevents this class from creating things like bootstrap menus and AdminLTE menus without a custom template.

An AdminLTE menu looks like this:

```html
<!-- Sidebar Menu -->
<ul class="sidebar-menu">
    <li class="header">HEADER</li>
    <!-- Optionally, you can add icons to the links -->
    <li class="active"><a href="#"><i class='fa fa-link'></i> <span>Link</span></a></li>
    <li><a href="#"><i class='fa fa-link'></i> <span>Another Link</span></a></li>
    <li class="treeview">
        <a href="#"><i class='fa fa-link'></i> <span>Multilevel</span> <i class="fa fa-angle-left pull-right"></i></a>
        <ul class="treeview-menu">
            <li><a href="#">Link in level 2</a></li>
            <li><a href="#">Link in level 2</a></li>
        </ul>
    </li>
</ul><!-- /.sidebar-menu -->
```

... being able to include the class="treeview-menu" in the child UL would be a useful feature.  Currently it's not supported.

**Comment by delatbabel** [comment]
Perhaps add an $innerAttributes parameter on the asUl / asOl / asDiv functions for attributes to be applied to the inner UL/OL/DIV tags?  Then pass those into the render() function.

**Comment by moazam1** [comment]
I would like to use this menu in adminlte template. @delatbabel I love to know when you have solution for this problem.

**Comment by delatbabel** [comment]
I have added a PR for this however there is a fairly long queue of other outstanding PRs that are yet to be merged.

**Comment by moazam1** [comment]
Great, if I add your changes to the plugin what else do I need to do to make AdminLTE menu functional? I will appreciate if you can write down snippet :) Thanks

**Comment by delatbabel** [comment]
It really depends on how you're calling it. I can point you at https://github.com/delatbabel/nestedmenus for some examples, check in src/Renderers.

**Comment by tomothumb** [comment]
I faced same issue.
I will add PR #100 to my code. thanks.

**Comment by moazam1** [comment]
@tomothumb Great work. I will try PR next week.

**Comment by azraf** [comment]
Check my pull request: https://github.com/lavary/laravel-menu/pull/113
I had face this issue and solved it for AdminLTE template. 

After making the simple change in the builder class file, now I can use the AdminLTE by simply calling {!! $MyNavBar->asUl( array('class' => 'sidebar-menu','style'=>'adminLTE') ) !!} from my blade template file.

**Comment by tyteen4a03** [comment]
+1

**Comment by Vishnja** [comment]
+1

**Comment by achillesp** [comment]
I think there's a simpler way to do this.
You just need to do artisan vendor:publish to get the laravel-menu config and blade files in the app folders.
Then you can set this class and any other custom classes in the blade template that the menu items use.

You then call the menu with something like:

<ul class="sidebar-menu">
    @include(config('laravel-menu.views.sidebar-items'), array('items' => $mainNav->roots()))
</ul>

This uses the view that you set in the config file. In fact, you could implement more than one styling depending on where you use the menu in your template.

**Comment by HejVkt** [comment]
It is very simple works now. You should add option in the render 

        {!! Menu::get('mainMenu')->asUl(
            ['class' => 'nav navbar-nav'],
            ['class'=>'dropdown-menu']
        ) !!}
as a result 
  <ul class="nav navbar-nav">
	 <li>
		<ul class="dropdown-menu"></ul>
	 </li>
 </ul>

**Comment by bastienu** [comment]
I'm sorry, but what you did give the possibility to set the same class on **all** child-ul. But, sometimes, we need to put specific ids to the a child `ul`, like here :

```html
<li>
    <a></a>
    <ul> <!-- NEED TO PUT A SPECIFIC ID HERE -->
        <li></li>
    </ul>
</li>
```

How to do so? I can't find anything about this in the doc...

Thanks.
