### ISSUE TITLE
Sortby not working

### ISSUE THREAD

**Issue by arjenduinhouwer** [lavary/laravel-menu#93]
First, let me Thank you for this package, it has already saved me a ton of time so far. 

I have an issue with the sorting function though, it doesn't seem to work at all. I've created a test menu with just the bare minimum to make sure I wasn't messing up myself. 

So essentially this would work right?

```
Menu::make('mainMenu', function($menu){
    $menu->add('home')->data('order', 1);
    $menu->add('contact')->data('order', 3);
    $menu->add('about')->data('order', 2);
}).sortBy('order');

```
I would expect:
1.home
2.about
3.contact

but the given order is ignored and the result is:

1.home
2.contact
3.about

Is anyone else having this issue?

**Comment by mastrip2** [comment]
I had this same problem. This person fixed the sort issue. Not sure why it wasnt committed to the main branch
https://github.com/lavary/laravel-menu/pull/72

**Comment by arjenduinhouwer** [comment]
Thanks, will look into it!

**Comment by lavary** [comment]
This issue has been fixed in the latest release. please update the package.

Thanks for using the package.

**Comment by lavary** [comment]
Closing the issue, feel free to reopen if you face a problem.
