### ISSUE TITLE
best place for defining menu items

### ISSUE THREAD

**Issue by amin101** [lavary/laravel-menu#94]
where is suitable place for defining menu? I'm not comfortable by `routes.php`

**Comment by neposoft** [comment]
What I do is make a new class for defining menu items and in my `AppServiceProvider`, I put ` \View::composer('*', NavicationComposer::class);`
Hope it helps

**Comment by lavary** [comment]
@amin101 It's been answered [here](https://github.com/lavary/laravel-menu/issues/89#issuecomment-156173586)

Thanks.

**Comment by lavary** [comment]
Closing the issue. Please feel free to reopen if you face the issue again.
