### ISSUE TITLE
find item using where returns empty collection

### ISSUE THREAD

**Issue by mastrip2** [lavary/laravel-menu#95]
If I try this example from the docs I dont get anything returned but only a empty collection. But if I try $menu->whereId(2); I get the about item. How can I use where to find custom data attributes?

    <?php
        Menu::make('MyNavBar', function($menu){

            $menu->add('Home',     '#')->data('color', 'red');
            $menu->add('About',    '#')->data('color', 'blue');
            $menu->add('Services', '#')->data('color', 'red');
            $menu->add('Contact',  '#')->data('color', 'green');

            // Fetch all the items with color set to red:
            $reds = $menu->whereColor('red');
            dd($reds);
        });

**Comment by lavary** [comment]
The issue has been fixed in the new release.  Please update the package.

**Comment by lavary** [comment]
Closing the issue, feel free to reopen if you face a problem.
